import { useEffect, useRef, useState } from 'react';
import api from '../../services/api';
import { normalizeImageUrl } from '../../services/normalize';
import { RentalField, RentalSummary } from './RentalUi';
import { rentalInstant, rentalMoney, rentalOperation, rentalUrl } from '../../utils/rentals';
import { RentalWaitlistJoin } from './RentalWaitlist';
import { RentalBookingDetailsFields } from './RentalBookingDetails';
import { editableRentalDetails, rentalDetailsPayload, validateRentalDetails } from '../../utils/rentalDetails';
export default function RentalBookingForm({ listings = [], visibleIds, configuration, user, apiBase = '/rentals', counter = false, initialProductId, initialItems, initialSchedule, onScheduleChange, storeSlug, onBooked }) {
  const [form, setForm] = useState({ pickupAt: '', returnDueAt: '', eventAt: '', deliveryMode: configuration?.policy?.deliveryModes?.[0] || 'STORE_PICKUP', address: '', name: user?.name || '', phone: user?.phone || '', email: user?.email || '', whatsappConsent: false });
  const [details, setDetails] = useState(() => editableRentalDetails(null, counter ? {} : user));
  const [selected, setSelected] = useState({}), [quoted, setQuoted] = useState(null), [accepted, setAccepted] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const attempt = useRef(rentalOperation()), lock = useRef(false), initialSelection = useRef(false);
  const [waitlistRequest, setWaitlistRequest] = useState(null);
  const initialPickup = initialSchedule?.pickupAt, initialReturn = initialSchedule?.returnDueAt, initialDelivery = initialSchedule?.deliveryMode;
  useEffect(() => {
    const schedule = { pickupAt: initialPickup, returnDueAt: initialReturn, deliveryMode: initialDelivery };
    if (Object.values(schedule).every(value => value === undefined)) return;
    setForm(f => {
      const patch = Object.fromEntries(['pickupAt', 'returnDueAt', 'deliveryMode'].filter(key => schedule[key] !== undefined && schedule[key] !== f[key]).map(key => [key, schedule[key]]));
      if (!Object.keys(patch).length) return f;
      return { ...f, ...patch };
    });
    setQuoted(null); setAccepted(false); setWaitlistRequest(null); attempt.current = rentalOperation();
  }, [initialPickup, initialReturn, initialDelivery]);
  useEffect(() => { if (initialItems?.length) { setSelected(old => { const next = { ...old }; for (const item of initialItems) { const quantity = item.replaces ? next[item.replaces] || item.quantity : item.quantity; if (item.replaces) delete next[item.replaces]; next[item.listingId] = quantity; } return next; }); initialSelection.current = true; setQuoted(null); setAccepted(false); setWaitlistRequest(null); attempt.current = rentalOperation(); } }, [initialItems]);
  useEffect(() => { if (!initialSelection.current && initialProductId && listings.length) { const first = listings.find(l => String(l.productId) === initialProductId); if (first) { initialSelection.current = true; setSelected(s => ({ ...s, [first._id]: 1 })); } } }, [initialProductId, listings]);
  const change = (key, value) => { setForm(f => ({ ...f, [key]: value })); if (['pickupAt', 'returnDueAt', 'deliveryMode'].includes(key)) onScheduleChange?.(key, value); setQuoted(null); setAccepted(false); setWaitlistRequest(null); attempt.current = rentalOperation(); };
  const select = (listingId, quantity) => { setSelected(s => { const next = { ...s }; if (quantity) next[listingId] = quantity; else delete next[listingId]; return next; }); setQuoted(null); setAccepted(false); setWaitlistRequest(null); attempt.current = rentalOperation(); };
  const changeDetails = value => { setDetails(value); setQuoted(null); setAccepted(false); setWaitlistRequest(null); attempt.current = rentalOperation(); };
  const payload = () => ({ pickupAt: rentalInstant(form.pickupAt, configuration.policy.timezone), returnDueAt: rentalInstant(form.returnDueAt, configuration.policy.timezone), ...(form.eventAt ? { eventAt: rentalInstant(form.eventAt, configuration.policy.timezone) } : {}), items: Object.entries(selected).map(([listingId, quantity]) => ({ listingId, quantity })), deliveryMode: form.deliveryMode, bookingDetails: rentalDetailsPayload(details, form.deliveryMode) });
  const review = async () => {
    const validation = validateRentalDetails(details, form.deliveryMode);
    if (validation) { setError(validation); setQuoted(null); setAccepted(false); return; }
    if (lock.current) return; lock.current = true; setBusy(true); setError(''); setAccepted(false);
    try { setQuoted(await api.post(rentalUrl(`${apiBase}/quote`, storeSlug), payload(), { silent: true })); }
    catch (e) { setQuoted(null); if (e.code === 'OUT_OF_STOCK' && !counter && configuration.policy.waitlistEnabled) setWaitlistRequest(payload()); setError(e.details || e.message); }
    finally { lock.current = false; setBusy(false); }
  };
  const book = async () => {
    if (lock.current || !quoted || !accepted) return; lock.current = true; setBusy(true); setError('');
    try { const booking = await api.post(rentalUrl(`${apiBase}/bookings`, storeSlug), { ...payload(), attemptId: attempt.current, policyRevision: quoted.policyRevision, quoteFingerprint: quoted.quoteFingerprint, acceptTerms: true, customer: { name: form.name, phone: form.phone, email: form.email, whatsappConsent: form.whatsappConsent } }, { silent: true }); onBooked(booking); }
    catch (e) { if (e.code === 'RENTAL_QUOTE_CHANGED') { setQuoted(null); setAccepted(false); attempt.current = rentalOperation(); } setError(e.details || e.message); }
    finally { lock.current = false; setBusy(false); }
  };
  if (!configuration) return null;
  return <div className="rental-grid"><section className="rental-card"><h2>{counter ? 'New counter / phone booking' : 'Plan your rental'}</h2><p className="rental-muted">All dates use {configuration.policy.timezone}. Every selected item shares this rental period. Choose product sizes before reviewing availability.</p>{error && <p role="alert" className="rental-notice">{error}</p>}<fieldset disabled={busy}><div className="rental-fields"><RentalField label="Pickup / delivery time" type="datetime-local" step={configuration.policy.slotMinutes * 60} value={form.pickupAt} onChange={v => change('pickupAt', v)} /><RentalField label="Return deadline" type="datetime-local" step={configuration.policy.slotMinutes * 60} value={form.returnDueAt} onChange={v => change('returnDueAt', v)} /><RentalField label="Event time (optional)" type="datetime-local" value={form.eventAt} onChange={v => change('eventAt', v)} /><RentalField label="Delivery method"><select value={form.deliveryMode} onChange={e => change('deliveryMode', e.target.value)}>{configuration.policy.deliveryModes.map(v => <option key={v} value={v}>{v.replace(/_/g, ' ')}</option>)}</select></RentalField></div>
    <RentalBookingDetailsFields value={details} onChange={changeDetails} deliveryMode={form.deliveryMode} />
    {waitlistRequest && <RentalWaitlistJoin request={waitlistRequest} user={user} storeSlug={storeSlug} />}
    <h3>Outfits, jewellery and accessories</h3>{!listings.length && <p className="rental-muted">No rental listings are available on this page.</p>}{listings.filter(l => !visibleIds || visibleIds.includes(l._id) || selected[l._id]).map(l => { const url = normalizeImageUrl(l.product?.images?.[0]?.url || l.product?.images?.[0]); return <label key={l._id} className="rental-choice"><input aria-label={`Select ${l.title}`} type="checkbox" checked={!!selected[l._id]} onChange={e => select(l._id, e.target.checked ? 1 : 0)} />{url && <img src={url} alt="" loading="lazy" />}<div><strong>{l.title}</strong><p className="rental-muted">{[l.size, l.colour].filter(Boolean).join(' · ')} · {rentalMoney(l.dailyRatePaise)}/day</p><p className="rental-muted">Deposit {rentalMoney(l.depositPaise)}{l.packages?.length ? ` · Packages: ${l.packages.map(p => `${p.days}d ${rentalMoney(p.pricePaise)}`).join(', ')}` : ''}</p></div>{selected[l._id] && <input aria-label={`Quantity for ${l.title}`} type="number" min="1" max="10" value={selected[l._id]} onChange={e => select(l._id, Math.min(10, Math.max(1, Number(e.target.value))))} />}</label>; })}
    <h3>Booking contact</h3><div className="rental-fields"><RentalField label="Customer name" value={form.name} onChange={v => change('name', v)} maxLength="100" /><RentalField label="Phone" value={form.phone} onChange={v => change('phone', v)} disabled={!counter} type="tel" /><RentalField label="Email for booking updates (optional)" value={form.email} onChange={v => change('email', v)} type="email" /></div><label className="rental-check"><input type="checkbox" checked={form.whatsappConsent} onChange={e => change('whatsappConsent', e.target.checked)} />I agree to receive transactional rental updates on WhatsApp. This does not subscribe me to marketing.</label><div className="rental-actions"><button type="button" className="rental-button" disabled={busy || !Object.keys(selected).length} onClick={review}>{busy ? 'Checking…' : 'Check dates & review price'}</button></div></fieldset></section>
    <aside>{quoted ? <><RentalSummary quoted={quoted} /><section className="rental-card"><h2>Review and reserve</h2><p className="rental-muted">Dates are secured only after the reservation succeeds. A short hold is not a confirmed booking. The compulsory owner-configured advance must be verified before confirmation. Full remaining rent and deposit are required before handover.</p><div className="rental-terms">{quoted.terms}</div>{quoted.policySummary && <div className="rental-muted"><p>Return grace: {quoted.policySummary.graceHours} hours · proposed late fee {rentalMoney(quoted.policySummary.lateFeePerDayPaise)} per started day; any deduction requires itemised approval.</p><p>Compulsory advance: {quoted.policySummary.advanceMode === 'FIXED' ? rentalMoney(quoted.policySummary.advanceAmountPaise) + ' (capped at rental charges)' : (quoted.policySummary.advancePercent ?? 30) + '% of rental charges'}. Security deposit: {quoted.policySummary.depositTiming === 'PICKUP' ? 'due at pickup' : 'due with booking advance'}.</p><p>No-show after {quoted.policySummary.noShowGraceHours ?? 24} hours: retain up to {quoted.policySummary.noShowRetainPercent ?? 100}% of rental charges, capped at rent paid; deposit refundable. Early return: {quoted.policySummary.earlyReturnPolicy === 'ACTUAL_DAYS' ? 'recalculate whole days, subject to minimum rental duration; services remain payable' : 'agreed rental period remains payable'}.</p>{(quoted.policySummary.requireConditionPhotos || quoted.policySummary.requireCustomerAcknowledgement) && <p>Condition photos {quoted.policySummary.requireConditionPhotos ? 'required' : 'optional'}; verified customer condition acknowledgement {quoted.policySummary.requireCustomerAcknowledgement ? 'required' : 'optional'} at handover and return.</p>}<h3>Cancellation retention</h3>{quoted.policySummary.cancellationRules.map((rule, i) => <p key={i}>At least {rule.beforeHours} hours before pickup: retain up to {rule.retainPercent}% of the rental charge, capped at rent already paid. Deposit is refundable after cancellation.</p>)}</div>}<label className="rental-check"><input type="checkbox" checked={accepted} onChange={e => setAccepted(e.target.checked)} />I accept these rental terms, the pickup/return deadline and the price breakdown.</label><button type="button" className="rental-button" disabled={busy || !accepted} onClick={book}>{busy ? 'Reserving…' : 'Reserve rental'}</button></section></> : <section className="rental-card"><h2>A complete look, without the guesswork</h2><p className="rental-muted">Select your outfit and accessories, choose pickup and return slots, and review the refundable deposit before reserving. Cleaning and preparation time are included in the availability check.</p></section>}</aside></div>;
}
