import { RentalField } from './RentalUi';
import { pieceMeasurementFields } from '../../utils/rentalDetails';
export default function RentalPieceMeasurements({ value, onChange, disabled }) {
  const fields = pieceMeasurementFields[value?.kind] || [];
  const update = (key, next) => onChange({ ...value, [key]: next });
  return <fieldset disabled={disabled} className="rental-detail-section"><legend>Structured physical-piece measurements</legend><p className="rental-muted">Actual garment / jewellery dimensions, not a customer body profile. These optional fields do not change stock, rental pricing or the product size chart. All dimensions and alteration limits use the selected unit.</p>
    <div className="rental-fields"><RentalField label="Piece measurement type"><select value={value?.kind || 'NONE'} onChange={e => (Object.keys(value?.values || {}).length && !window.confirm('Changing measurement type clears existing structured dimensions and alteration limits. Continue?')) ? undefined : onChange(e.target.value === 'NONE' ? null : { kind: e.target.value, unit: value?.unit || 'in', values: {}, alterationsAllowed: false, alterationLimits: {}, notes: value?.notes || '' })}><option value="NONE">Not recorded</option><option value="APPAREL">Outfit / garment</option><option value="JEWELLERY">Jewellery / bangles</option><option value="OTHER">Other accessory</option></select></RentalField>{value && <RentalField label="Piece measurement unit"><select value={value.unit} onChange={e => { if (Object.values(value.values || {}).some(number => number !== '') && !window.confirm('Convert all piece dimensions and alteration limits to the new unit?')) return; const factor = e.target.value === 'cm' ? 2.54 : 1 / 2.54, convert = number => number === '' ? '' : Math.round(Number(number) * factor * 100) / 100; onChange({ ...value, unit: e.target.value, values: Object.fromEntries(Object.entries(value.values).map(([key, number]) => [key, convert(number)])), alterationLimits: Object.fromEntries(Object.entries(value.alterationLimits).map(([key, limit]) => [key, { min: convert(limit.min), max: convert(limit.max) }])) }); }}><option value="in">Inches</option><option value="cm">Centimetres</option></select></RentalField>}</div>
    {value && <><div className="rental-fields">{fields.map(([key, label]) => <RentalField key={key} label={`Piece ${label.toLowerCase()} (${value.unit})`} type="number" min="0.01" step="0.01" value={value.values[key] ?? ''} onChange={next => { const limits = { ...value.alterationLimits }; if (next === '') delete limits[key]; onChange({ ...value, values: { ...value.values, [key]: next }, alterationLimits: limits }); }} />)}</div><label className="rental-check"><input type="checkbox" checked={value.alterationsAllowed} onChange={e => onChange({ ...value, alterationsAllowed: e.target.checked, alterationLimits: e.target.checked ? value.alterationLimits : {} })} />This physical piece may be altered</label>{value.alterationsAllowed && <><p className="rental-muted">Optional absolute minimum/maximum finished dimensions. Enter both bounds for each dimension you want to limit. Current size must fit within its range; an empty range means no limit recorded, not unlimited permission.</p>{fields.filter(([key]) => value.values[key] !== undefined && value.values[key] !== '').map(([key, label]) => <div className="rental-fields" key={key}>{[['min', 'Minimum'], ['max', 'Maximum']].map(([bound, title]) => <RentalField key={bound} label={`${label} alteration ${title.toLowerCase()} (${value.unit})`} type="number" min="0.01" step="0.01" value={value.alterationLimits[key]?.[bound] ?? ''} onChange={next => update('alterationLimits', { ...value.alterationLimits, [key]: { min: '', max: '', ...value.alterationLimits[key], [bound]: next } })} />)}</div>)}</>}<RentalField label="Physical-piece measurement / alteration notes" multiline maxLength="1000" value={value.notes || ''} onChange={next => update('notes', next)} /></>}
  </fieldset>;
}
