import { RentalField } from './RentalUi';
import { rentalAddressFields, rentalAddressText } from '../../utils/rentalDetails';
import { rentalDate } from '../../utils/rentals';
export function RentalBookingDetailsFields({ value, onChange, deliveryMode, outboundLocked = false, legacyDeliveryAddress }) {
  const change = (key, next) => onChange({ ...value, [key]: next });
  const address = (key, label, disabled = false) => <fieldset disabled={disabled} className="rental-detail-section"><legend>{label}</legend><div className="rental-fields">{rentalAddressFields.map(([field, title]) => <RentalField key={field} label={`${label} — ${title}`} value={value[key]?.[field] || ''} type={field === 'mobile' ? 'tel' : 'text'} inputMode={['mobile', 'pincode'].includes(field) ? 'numeric' : undefined} maxLength={field === 'pincode' ? 6 : field === 'fullName' ? 100 : field === 'mobile' ? 25 : 120} onChange={next => change(key, { ...value[key], [field]: next })} />)}</div></fieldset>;
  return <div className="rental-detail-fields">
    {deliveryMode !== 'STORE_PICKUP' && <>{legacyDeliveryAddress ? <div className="rental-detail-section"><h3>Original delivery address (legacy · locked)</h3><p className="rental-muted">{legacyDeliveryAddress}</p></div> : address('deliveryAddress', 'Delivery address', outboundLocked)}<label className="rental-check"><input type="checkbox" checked={value.sameAsDelivery} onChange={e => change('sameAsDelivery', e.target.checked)} />Return collection address is the same as delivery</label>{!value.sameAsDelivery && address('collectionAddress', 'Return collection address')}</>}
    <details><summary>Alternate contact & authorised pickup / return people</summary><p className="rental-muted">Optional. Booking ownership, login and refunds stay with the original customer. Authorisation is recorded; it does not automatically verify another person’s phone or identity.</p>
      {[['alternateContact', 'Alternate contact'], ['pickupContact', 'Pickup / delivery contact'], ['returnContact', 'Return contact']].map(([key, label]) => <fieldset key={key} disabled={outboundLocked && key === 'pickupContact'} className="rental-detail-section"><legend>{label}</legend><label className="rental-check"><input type="checkbox" checked={!!value[key]} onChange={e => change(key, e.target.checked ? { name: '', phone: '', ...(key !== 'alternateContact' ? { relationship: '', authorised: false } : {}) } : null)} />{key === 'alternateContact' ? 'Add an alternate contact' : `Someone else will handle ${key === 'pickupContact' ? 'pickup / delivery' : 'return'}`}</label>{value[key] && <><div className="rental-fields"><RentalField label={`${label} — Name`} maxLength="100" value={value[key].name} onChange={next => change(key, { ...value[key], name: next })} /><RentalField label={`${label} — Mobile number`} type="tel" inputMode="numeric" maxLength="25" value={value[key].phone} onChange={next => change(key, { ...value[key], phone: next })} />{key !== 'alternateContact' && <RentalField label={`${label} — Relationship (optional)`} maxLength="100" value={value[key].relationship} onChange={next => change(key, { ...value[key], relationship: next })} />}</div>{key !== 'alternateContact' && <label className="rental-check"><input type="checkbox" checked={value[key].authorised} onChange={e => change(key, { ...value[key], authorised: e.target.checked })} />Customer explicitly authorises this {key === 'pickupContact' ? 'pickup / delivery' : 'return'} contact</label>}</>}</fieldset>)}
    </details>
    <details><summary>Occasion & special instructions (optional)</summary><fieldset disabled={outboundLocked}><RentalField label="Occasion / event type (optional)" value={value.occasion} maxLength="100" placeholder="Wedding, engagement, festival…" onChange={next => change('occasion', next)} /><RentalField label="Special fitting instructions (optional)" multiline maxLength="1000" value={value.fittingInstructions} onChange={next => change('fittingInstructions', next)} /></fieldset><RentalField label="Delivery / collection instructions (optional)" multiline maxLength="1000" value={value.deliveryInstructions} onChange={next => change('deliveryInstructions', next)} /><p className="rental-muted">Requests are subject to store confirmation. Do not enter payment credentials, identity documents or access codes.</p></details>
  </div>;
}
export default function RentalBookingDetails({ booking }) {
  const value = booking.bookingDetails;
  if (!value) return null;
  return <section className="rental-card rental-booking-details"><h2>Booking details & authorised contacts</h2>
    {booking.schedule?.eventAt && <p className="rental-muted">Event: {rentalDate(booking.schedule.eventAt, booking.policy?.timezone)}</p>}
    {value.occasion && <p><strong>Occasion:</strong> {value.occasion}</p>}
    {value.deliveryAddress && <div className="rental-detail-section"><h3>Delivery address</h3><p>{rentalAddressText(value.deliveryAddress)}</p><h3>Return collection address{value.sameAsDelivery ? ' · same as delivery' : ''}</h3><p>{rentalAddressText(value.collectionAddress)}</p></div>}
    {!value.deliveryAddress && booking.logistics?.address && <div className="rental-detail-section"><h3>Original delivery address</h3><p>{booking.logistics.address}</p><h3>Return collection address</h3><p>{value.collectionAddress ? rentalAddressText(value.collectionAddress) : booking.logistics.address}</p></div>}
    {[['alternateContact', 'Alternate contact'], ['pickupContact', 'Authorised pickup / delivery contact'], ['returnContact', 'Authorised return contact']].map(([key, label]) => value[key] && <div key={key} className="rental-detail-section"><h3>{label}</h3><p>{value[key].name} · {value[key].phone}{value[key].relationship && ` · ${value[key].relationship}`}</p>{key !== 'alternateContact' && <p className="rental-muted">Customer authorisation recorded{value[key].authorisedAt && ` ${rentalDate(value[key].authorisedAt, booking.policy?.timezone)}`}. Staff must review the named contact before handing over / receiving pieces.</p>}</div>)}
    {value.fittingInstructions && <div><h3>Fitting instructions</h3><p className="rental-preserve-text">{value.fittingInstructions}</p></div>}
    {value.deliveryInstructions && <div><h3>Delivery / collection instructions</h3><p className="rental-preserve-text">{value.deliveryInstructions}</p></div>}
    {!!booking.contactChecks?.length && <details><summary>Contact checks ({booking.contactChecks.length})</summary>{booking.contactChecks.map(check => <p key={check.operationId} className="rental-muted">{check.stage === 'HANDOVER' ? 'Handover' : 'Return'} · {check.name} · {check.phone} · {rentalDate(check.checkedAt, booking.policy?.timezone)}</p>)}</details>}
  </section>;
}
