import { useCallback, useEffect, useRef, useState } from 'react';
import api from '../../services/api';
import { RentalField } from './RentalUi';
import { announceSettingsSaved } from '../../config/storeSettings';
import RentalPolicyControls from './RentalPolicyControls';
import RentalStudioSettings from './RentalStudioSettings';
const noop = () => {};
export default function RentalSettings({ apiBase = '/admin/rentals', onDirtyChange = noop, onBusyChange = noop }) {
  const [form, setForm] = useState(null), [baseline, setBaseline] = useState(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [saved, setSaved] = useState('');
  const lock = useRef(false);
  const lastEnabledMode = useRef('SALE_AND_RENTAL');
  const load = useCallback(async () => { try { const value = await api.get(`${apiBase}/configuration`, { silent: true }); setForm(value); setBaseline(value); setError(''); } catch (e) { setError(e.message); } }, [apiBase]);
  useEffect(() => { load(); }, [load]);
  const dirty = !!form && JSON.stringify(form) !== JSON.stringify(baseline);
  useEffect(() => { onDirtyChange(dirty); }, [dirty, onDirtyChange]);
  useEffect(() => { onBusyChange(busy); }, [busy, onBusyChange]);
  useEffect(() => () => { onDirtyChange(false); onBusyChange(false); }, [onDirtyChange, onBusyChange]);
  const change = (key, value) => { setSaved(''); setForm(f => ({ ...f, policy: { ...f.policy, [key]: value } })); };
  const save = async () => {
    if (lock.current) return; lock.current = true; setBusy(true); setError(''); setSaved('');
    try { const value = await api.put(`${apiBase}/configuration`, form, { silent: true }); setForm(value); setBaseline(value); announceSettingsSaved(); setSaved('Rental settings saved. Existing bookings retain their accepted pricing and terms.'); }
    catch (e) { setError(e.details || e.message); }
    finally { lock.current = false; setBusy(false); }
  };
  if (!form) return <div role="status">{error || 'Loading rental preferences…'}{error && <button type="button" onClick={load} className="rental-button">Retry</button>}</div>;
  const p = form.policy;
  if (form.mode !== 'SALE_ONLY') lastEnabledMode.current = form.mode;
  const numbers = [['holdMinutes', 'Checkout hold (minutes)'], ['minimumDays', 'Minimum rental days'], ['maximumDays', 'Maximum rental days'], ['minimumLeadHours', 'Booking lead time (hours)'], ['maximumAdvanceDays', 'Book ahead (days)'], ['preparationHours', 'Preparation buffer (hours)'], ['cleaningHours', 'Return/cleaning buffer (hours)'], ['balanceDueHours', 'Balance due before pickup (hours)'], ['graceHours', 'Return grace (hours)'], ['slotMinutes', 'Slot duration (minutes)'], ['slotCapacity', 'Bookings per pickup/return slot']];
  return <div className="rental-settings"><p className="rental-notice">Rental pieces are separate from sale stock. A return deadline does not automatically restock a piece; inspection and cleaning must be completed. Transaction-capable MongoDB is required.</p>{error && <p className="rental-notice" role="alert">{error}</p>}{saved && <p role="status" className="rental-notice">{saved}</p>}<fieldset disabled={busy}>
    <label className="rental-check"><input type="checkbox" aria-label="Enable rental shopping" checked={form.mode !== 'SALE_ONLY'} onChange={e => { setSaved(''); setForm(f => ({ ...f, mode: e.target.checked ? lastEnabledMode.current : 'SALE_ONLY' })); }} />Enable rental shopping</label><p className="rental-muted">Shows rental shopping on desktop, mobile and product details. Turning this off stops new rentals and restores sale-only shopping. Existing bookings, pickup, returns and deposits remain accessible.</p>
    <RentalPolicyControls policy={p} onChange={change} />
    <RentalStudioSettings policy={p} onChange={change} />
    <div className="rental-fields"><RentalField label="Business operations"><select value={form.mode} onChange={e => setForm(f => ({ ...f, mode: e.target.value }))}><option value="SALE_ONLY">Sale only — rentals off</option><option value="RENTAL_ONLY">Rental only</option><option value="SALE_AND_RENTAL">Sale and rental</option></select></RentalField><RentalField label="Store timezone" value={p.timezone} onChange={v => change('timezone', v)} />{numbers.map(([key, label]) => <RentalField key={key} label={label} type="number" min="0" step="1" value={p[key]} onChange={v => change(key, v === '' ? '' : Number(v))} />)}{[['lateFeePerDayPaise', 'Late fee per started day (₹; proposed, not auto-deducted)'], ['deliveryFeePaise', 'Delivery charge (₹)'], ['returnFeePaise', 'Return collection charge (₹)']].map(([key, label]) => <RentalField key={key} label={label} type="number" min="0" step="0.01" value={Number(p[key]) / 100} onChange={v => change(key, Math.round(Number(v) * 100))} />)}<RentalField label="Shop opens" type="time" value={p.pickupStart} onChange={v => change('pickupStart', v)} /><RentalField label="Shop closes" type="time" value={p.pickupEnd} onChange={v => change('pickupEnd', v)} /></div>
    <h3>Pickup and collection</h3>{['STORE_PICKUP', 'SELF_DELIVERY', 'COURIER'].map(mode => <label className="rental-check" key={mode}><input type="checkbox" checked={p.deliveryModes.includes(mode)} onChange={e => change('deliveryModes', e.target.checked ? [...p.deliveryModes, mode] : p.deliveryModes.filter(v => v !== mode))} />{mode.replace(/_/g, ' ')}</label>)}<p className="rental-muted">Courier mode supports manual tracking or the optional connected carrier controls on each booking. Integrated outbound and reverse pickups require Delivery settings, carrier credentials and shipping automation access. Staff explicitly book each leg; physical piece handover and return remain separate checks.</p>
    <h3>Closures and holidays</h3><div className="rental-actions">{['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((day, index) => <label className="rental-check" key={day}><input type="checkbox" checked={p.closedWeekdays.includes(index)} onChange={e => change('closedWeekdays', e.target.checked ? [...p.closedWeekdays, index] : p.closedWeekdays.filter(v => v !== index))} />{day}</label>)}</div><RentalField label="Holiday dates (YYYY-MM-DD, comma-separated)" value={p.closedDates.join(', ')} onChange={v => change('closedDates', v.split(',').map(s => s.trim()).filter(Boolean))} />
    <h3>Cancellation rules</h3><p className="rental-muted">Highest matching notice period applies. Include a zero-hour rule. Refundable deposit is settled separately.</p>{p.cancellationRules.map((rule, index) => <div className="rental-fields" key={index}><RentalField label="At least this many hours before pickup" type="number" min="0" value={rule.beforeHours} onChange={v => change('cancellationRules', p.cancellationRules.map((r, i) => i === index ? { ...r, beforeHours: Number(v) } : r))} /><RentalField label="Rent retained (%)" type="number" min="0" max="100" value={rule.retainPercent} onChange={v => change('cancellationRules', p.cancellationRules.map((r, i) => i === index ? { ...r, retainPercent: Number(v) } : r))} /><button type="button" className="rental-button rental-button--secondary" onClick={() => change('cancellationRules', p.cancellationRules.filter((_, i) => i !== index))}>Remove rule</button></div>)}<button type="button" className="rental-button rental-button--secondary" disabled={p.cancellationRules.length >= 10} onClick={() => change('cancellationRules', [...p.cancellationRules, { beforeHours: 24, retainPercent: 50 }])}>Add cancellation rule</button>
    <h3>Rental FAQs visible before booking</h3><p>Write your actual policy for fittings, included components, advances/security, cancellation, late returns, cleaning, damage and refund timing.</p>{(p.faqs || []).map((row, index) => <section className="rental-card" key={index}><RentalField label={`FAQ ${index + 1} question`} value={row.question} maxLength="200" onChange={value => change('faqs', p.faqs.map((item, i) => i === index ? { ...item, question: value } : item))} /><RentalField label={`FAQ ${index + 1} answer`} value={row.answer} multiline rows="3" maxLength="2000" onChange={value => change('faqs', p.faqs.map((item, i) => i === index ? { ...item, answer: value } : item))} /><button type="button" onClick={() => change('faqs', p.faqs.filter((_, i) => i !== index))}>Remove FAQ</button></section>)}<button type="button" disabled={(p.faqs || []).length >= 20} onClick={() => change('faqs', [...(p.faqs || []), { question: '', answer: '' }])}>Add rental FAQ</button>
    <h3>Customer agreement</h3><RentalField label="Rental terms (shown before booking; versioned on acceptance)" multiline rows="6" value={p.terms} onChange={v => change('terms', v)} />
    <h3>Transactional reminders</h3><p className="rental-muted">In-app updates are always available. Email/WhatsApp use this store’s encrypted credentials from Order alerts. WhatsApp needs a separate approved rental utility template with five text variables: store name, booking number, amount, event title, secure link. Customer WhatsApp requires explicit consent.</p>{[['ownerEmail', 'Owner email'], ['ownerWhatsapp', 'Owner WhatsApp'], ['customerEmail', 'Customer email'], ['customerWhatsapp', 'Customer WhatsApp']].map(([key, label]) => <label key={key} className="rental-check"><input type="checkbox" checked={p[key]} onChange={e => change(key, e.target.checked)} />{label}</label>)}<div className="rental-fields"><RentalField label="Rental WhatsApp template" value={p.whatsappTemplate} onChange={v => change('whatsappTemplate', v)} /><RentalField label="Template language" value={p.whatsappLanguage} onChange={v => change('whatsappLanguage', v)} /></div>
    <div className="rental-actions"><button type="button" disabled={!dirty || busy} className="rental-button" onClick={save}>{busy ? 'Saving…' : 'Save rental settings'}</button><button type="button" disabled={!dirty || busy} className="rental-button rental-button--secondary" onClick={() => { setForm(baseline); setError(''); }}>Discard</button><button type="button" disabled={busy} className="rental-button rental-button--secondary" onClick={() => { if (!dirty || window.confirm('Discard unsaved rental changes and reload the latest settings?')) load(); }}>Reload latest</button></div>
  </fieldset></div>;
}
