import { rentalCopy } from '../../utils/rentalCopy';
import { rentalDate, rentalMoney } from '../../utils/rentals';
import './Rentals.css';
export function RentalField({ label, value, onChange, multiline, children, ...props }) {
  return <label className="rental-field"><span>{label}</span>{children || (multiline ? <textarea value={value ?? ''} onChange={e => onChange(e.target.value)} {...props} /> : <input value={value ?? ''} onChange={e => onChange(e.target.value)} {...props} />)}</label>;
}
export function RentalStatus({ value, label }) { return <span className={`rental-status rental-status--${String(value).toLowerCase()}`}>{label || rentalCopy(value)}</span>; }
export function RentalSummary({ booking, quoted }) {
  const data = booking || quoted; if (!data) return null;
  const q = data.quote;
  return <section className="rental-card rental-summary"><h2>{booking ? booking.number : 'Your rental quote'}</h2>{booking && <RentalStatus value={booking.status} />}<p>Pickup: {rentalDate(data.schedule.pickupAt, booking?.policy?.timezone || quoted.timezone)}</p><p>Return by: {rentalDate(data.schedule.returnDueAt, booking?.policy?.timezone || quoted.timezone)}</p>{data.schedule.days && <p className="rental-muted">Charged rental duration: {data.schedule.days} {data.schedule.days === 1 ? 'day' : 'days'}. {data.schedule.billingBasis === 'USE_DAYS' ? 'Only the selected use days add rent. Pickup and return days outside them add no rent.' : 'Rent is calculated from the agreed pickup and return times.'}</p>}<div>{(q.items || []).map(item => <div className="rental-muted" key={item.listingId}><strong>{item.title} × {item.quantity}</strong>{item.fitting && <div className="rental-fitting-info"><p>{item.fitting.adjustable && <span>Adjustable fitting</span>}{item.fitting.alterationsAvailable && <span>Stitching / alterations available</span>}</p>{item.fitting.instructions && <p>{item.fitting.instructions}</p>}</div>}<p>Rent {rentalMoney(item.rentPaise)} · service fees {rentalMoney(item.feesPaise)} · deposit {rentalMoney(item.depositPaise)}</p>{item.components?.map((component, i) => <p key={i}>{component.label} × {component.quantity}</p>)}</div>)}</div><dl><div><dt>Rent & services</dt><dd>{rentalMoney(booking?.adjustedRentalPaise ?? q.rentalPaise)}</dd></div><div><dt>Refundable security deposit</dt><dd>{rentalMoney(q.depositPaise)}</dd></div><div><dt>{q.paymentPlan === 'PICKUP' ? 'Payment at pickup' : q.paymentPlan === 'FULL' ? 'Full payment now' : 'Booking advance'}</dt><dd>{rentalMoney(q.advanceRentPaise)}</dd></div><div><dt>Due to confirm booking{q.depositTiming === 'PICKUP' ? ' (deposit at pickup)' : ' (includes deposit)'}</dt><dd>{rentalMoney(q.dueNowPaise)}</dd></div><div><dt>Remaining at pickup</dt><dd>{rentalMoney(Math.max(0, (q.totalPaise ?? q.rentalPaise + q.depositPaise) - q.dueNowPaise))}</dd></div>{booking && <><div><dt>Collected</dt><dd>{rentalMoney(booking.financial.collectedPaise)}</dd></div><div><dt>Outstanding</dt><dd>{rentalMoney(booking.financial.balancePaise)}</dd></div><div><dt>Approved assessments</dt><dd>{rentalMoney(booking.financial.deductionsPaise)}</dd></div><div><dt>Refund available</dt><dd>{rentalMoney(booking.financial.refundablePaise)}</dd></div><div><dt>Refund processed</dt><dd>{rentalMoney(booking.financial.refundedPaise)}</dd></div></>}</dl><p className="rental-muted">Deposit is not rental income. Settlement follows inspection. Prices include applicable taxes; courier details are confirmed by the store.</p>{booking?.overdue && <p role="alert" className="rental-warning">Return overdue. Estimated late fee: {rentalMoney(booking.estimatedLateFeePaise)}; any deduction needs an itemised assessment.</p>}</section>;
}
