import { useEffect, useRef, useState } from 'react';
import { rentalOperation } from '../../utils/rentals';
import api from '../../services/api';
import { RentalField } from './RentalUi';
import RentalRecordPager from './RentalRecordPager';
import RentalProductPicker from './RentalProductPicker';
import ProductRentalPricing, { pricingFromOffer, rentalPricingError } from '../admin/ProductRentalPricing';
const newOffer = () => ({ productId: '', title: '', active: false, dailyRatePaise: '', depositPaise: 0, advanceMode: 'STORE', fitting: { adjustable: true, alterationsAvailable: true, instructions: '' }, cleaningFeePaise: 0, alterationFeePaise: 0, packages: [], requirements: [] });
const noop = () => {};
export default function RentalSetupWizard({ base, initialListingId = '', initialProductId = '', permissions = {}, readiness, configuration, refresh = 0, busy, run, onTab, onDirtyChange = noop }) {
  const [rows, setRows] = useState([]), [id, setId] = useState(initialListingId), [data, setData] = useState(null), [step, setStep] = useState(initialListingId ? 2 : 1);
  const [offer, setOffer] = useState(newOffer), [piece, setPiece] = useState({ component: '0', code: '', label: '', location: '', condition: 'Good' }), [error, setError] = useState(''), [loading, setLoading] = useState(false);
  const [reload, setReload] = useState(0), [quantity, setQuantity] = useState('');
  const batch = useRef(rentalOperation());
  useEffect(() => { batch.current = rentalOperation(); }, [id, quantity, piece.component, piece.location, piece.condition]);
  const registerQuantity = async () => {
    const count = Number(quantity);
    if (!Number.isInteger(count) || count < 1 || count > 100) { setError('Enter the actual new pieces you own, from 1 to 100.'); return; }
    const result = await run(() => api.post(`${base}/setup/${id}/pieces`, { operationId: batch.current, revision: data.listing.revision, componentIndex: Number(piece.component), quantity: count, location: piece.location, condition: piece.condition }));
    if (result) { batch.current = rentalOperation(); setQuantity(''); setReload(v => v + 1); }
  };
  const dirty = !loading && (JSON.stringify(offer) !== JSON.stringify(data?.listing || newOffer()) || !!piece.code.trim() || !!piece.label.trim());
  useEffect(() => { onDirtyChange(dirty); }, [dirty, onDirtyChange]);
  useEffect(() => () => onDirtyChange(false), [onDirtyChange]);
  useEffect(() => { if (initialListingId) setId(initialListingId); }, [initialListingId]);
  useEffect(() => { if (!initialListingId && initialProductId) setOffer(value => ({ ...value, productId: initialProductId })); }, [initialListingId, initialProductId]);
  useEffect(() => {
    if (!id) { setData(null); return undefined; }
    let alive = true; setLoading(true); setError(''); setData(null);
    api.get(`${base}/setup/${id}`, { silent: true, forceRefetch: true }).then(result => { if (!result?.listing || !Array.isArray(result.checks) || !Array.isArray(result.components)) throw new Error('Rental setup could not be loaded. Refresh readiness to retry.'); if (alive) { setData(result); setOffer(result.listing); setPiece(p => ({ ...p, component: '0' })); } }).catch(e => { if (alive) setError(e.details || e.message); }).finally(() => { if (alive) setLoading(false); });
    return () => { alive = false; };
  }, [base, id, refresh, reload]);
  const write = permissions['inventory.write'] !== false;
  const save = async () => {
    const pricing = pricingFromOffer({ ...offer, _id: offer._id });
    const problem = rentalPricingError(pricing);
    if (problem || !offer.productId) { setError(problem || 'Choose a catalogue product first.'); return; }
    setError('');
    const result = await run(() => api.post(`${base}/listings`, { ...offer, active: offer._id ? offer.active : false }));
    if (result) { setId(result._id); setOffer(result); setStep(2); setReload(v => v + 1); }
  };
  const addPiece = async () => {
    const component = data?.components[Number(piece.component)];
    if (!component) return;
    const result = await run(() => api.post(`${base}/assets`, { poolKey: component.poolKey, productId: component.productId || offer.productId, variantId: component.variantId || '', size: component.size || '', colour: component.colour || '', code: piece.code, label: piece.label || component.label, location: piece.location, condition: piece.condition }));
    if (result) { setPiece(p => ({ ...p, code: '', label: '' })); setReload(v => v + 1); }
  };
  const activate = async active => {
    if (!data) return;
    const result = await run(() => api.post(`${base}/listings`, { ...data.listing, active }));
    if (result) { setOffer(result); setReload(v => v + 1); }
  };
  return <section className="rental-card rental-setup" aria-busy={loading || busy}><span className="rental-eyebrow">MAKE AN OFFER READY</span><h2>Guided rental setup</h2><p className="rental-muted">Set the price, register the real pieces you own, and activate the offer when every component is configured.</p>
    <RentalRecordPager base={base} kind="listings" refresh={refresh} onLoaded={setRows} />
    <div className="rental-fields"><RentalField label="Offer to set up"><select value={id} disabled={busy || loading} onChange={e => { if (dirty && !window.confirm('Switch rental offer? Unsaved changes will be lost.')) return; setPiece(p => ({ ...p, code: '', label: '' })); setId(e.target.value); if (!e.target.value) setOffer(newOffer()); setStep(1); }}><option value="">New offer</option>{rows.map(row => <option key={row._id} value={row._id}>{row.title} · {row.active ? 'Active' : 'Paused'}</option>)}{id && !rows.some(row => row._id === id) && <option value={id}>{data?.listing.title || 'Selected offer'}</option>}</select></RentalField><button type="button" className="rental-button rental-button--secondary" disabled={busy} onClick={() => { if (dirty && !window.confirm('Start a new offer? Unsaved changes will be lost.')) return; setPiece(p => ({ ...p, code: '', label: '' })); setId(''); setOffer(newOffer()); setStep(1); }}>Create another rental offer</button><button type="button" className="rental-text-button" disabled={busy || loading || !id} onClick={() => { if (dirty && !window.confirm('Reload this offer? Unsaved changes will be lost.')) return; setReload(v => v + 1); }}>Refresh readiness</button></div>
    <nav className="rental-setup-steps" aria-label="Rental setup steps">{['Price & fitting', 'Physical pieces', 'Review & activate'].map((label, i) => <button type="button" key={label} className={step === i + 1 ? 'is-selected' : ''} aria-current={step === i + 1 ? 'step' : undefined} disabled={busy || loading || (i > 0 && !data)} onClick={() => setStep(i + 1)}><strong>{i + 1}</strong>{label}</button>)}</nav>
    {error && <p role="alert" className="rental-notice">{error}</p>}{loading && <p role="status">Checking this offer…</p>}
    {!loading && step === 1 && <fieldset disabled={busy || !write}><RentalProductPicker base={base} productId={offer.productId} disabled={!!offer._id} onChoose={product => setOffer(o => ({ ...o, productId: product._id, title: product.name, requirements: [{ poolKey: `product-${product._id}`, label: product.name.slice(0, 100), quantity: 1, productId: product._id }] }))} /><RentalField label="Offer title" maxLength={200} value={offer.title} onChange={title => setOffer(o => ({ ...o, title }))} /><ProductRentalPricing value={pricingFromOffer(offer)} offers={offer._id ? [offer] : []} apiPrefix={base.replace(/\/rentals$/, '')} onChange={pricing => setOffer(o => ({ ...o, ...pricing, fitting: pricing.fitting || o.fitting }))} /><div className="rental-fields"><RentalField label="Cleaning fee per set (₹)" type="number" min="0" step="0.01" value={offer.cleaningFeePaise / 100} onChange={value => setOffer(o => ({ ...o, cleaningFeePaise: Math.round(Number(value) * 100) }))} /><RentalField label="Alteration fee per set (₹)" type="number" min="0" step="0.01" value={offer.alterationFeePaise / 100} onChange={value => setOffer(o => ({ ...o, alterationFeePaise: Math.round(Number(value) * 100) }))} /></div><button type="button" className="rental-button" onClick={save}>Save price & continue</button><button type="button" className="rental-text-button" onClick={() => onTab('listings')}>Manage bundled components & duration packages →</button></fieldset>}
    {!loading && data && step === 2 && <><h3>Register actual pieces</h3><ul className="rental-setup-checks">{data.components.map(component => <li key={component.poolKey} className={component.configured >= component.required ? 'is-ready' : ''}><strong>{component.label}</strong><span>{component.configured} registered · {component.required} required per set · {component.readyNow} ready now</span></li>)}</ul><p className="rental-muted">Use a unique label/code for each physical item. These pieces are separate from sale stock. Pieces in cleaning or repair become bookable after staff release them.</p><fieldset disabled={busy || !write}><div className="rental-fields"><RentalField label="Component for this piece"><select value={piece.component} onChange={e => setPiece(p => ({ ...p, component: e.target.value }))}>{data.components.map((component, i) => <option key={component.poolKey} value={i}>{component.label}</option>)}</select></RentalField><RentalField label="Unique physical piece code" maxLength={80} value={piece.code} onChange={code => setPiece(p => ({ ...p, code }))} /><RentalField label="Piece label (optional)" maxLength={200} value={piece.label} onChange={label => setPiece(p => ({ ...p, label }))} /><RentalField label="Rack / location" maxLength={200} value={piece.location} onChange={location => setPiece(p => ({ ...p, location }))} /><RentalField label="Current condition" maxLength={1000} value={piece.condition} onChange={condition => setPiece(p => ({ ...p, condition }))} /></div><div className="rental-card"><h3>Generate codes for actual quantity</h3><RentalField label="New physical pieces to register (owner counted)" type="number" min="1" max="100" value={quantity} onChange={value => { setQuantity(value); batch.current = rentalOperation(); }} /><p className="rental-muted">Applies to the selected component, rack and condition above. Adds this quantity to existing pieces; sale stock is never copied. For a set, register each included component separately.</p><button type="button" className="rental-button" disabled={!quantity} onClick={registerQuantity}>Generate codes & register pieces</button></div><button type="button" className="rental-button" onClick={addPiece}>Register this piece</button><button type="button" className="rental-button rental-button--secondary" onClick={() => setStep(3)}>Review activation</button></fieldset></>}
    {!loading && data && step === 3 && <><h3>{data.listing.active ? 'Offer is active' : 'Ready to open bookings?'}</h3><ul className="rental-setup-checks">{data.checks.map(check => <li key={check.key} className={check.ready ? 'is-ready' : ''}><strong>{check.ready ? '✓' : '○'} {check.label}</strong></li>)}<li className={data.shopEnabled ? 'is-ready' : ''}><strong>{data.shopEnabled ? '✓' : '○'} Shop rental mode enabled</strong></li><li className={data.onlinePayments ? 'is-ready' : ''}><strong>{data.onlinePayments ? '✓' : '○'} Online payments enabled</strong></li><li className={data.acceptingOrders !== false ? 'is-ready' : ''}><strong>{data.acceptingOrders !== false ? '✓' : '○'} Shop accepting new orders</strong></li><li className={readiness.transactions ? 'is-ready' : ''}><strong>{readiness.transactions ? '✓' : '○'} Booking transactions available</strong></li></ul><p className="rental-muted">Registered pieces are checked here; date availability is checked separately with bookings, cleaning buffers and shop slots.</p><div className="rental-actions"><button type="button" className="rental-button" disabled={busy || !write || !data.ready || !data.shopEnabled || !readiness.transactions || data.listing.active} onClick={() => activate(true)}>Activate rental offer</button>{data.listing.active && <button type="button" className="rental-button rental-button--secondary" disabled={busy || !write} onClick={() => activate(false)}>Pause new bookings for this offer</button>}</div></>}
    <aside className="rental-launch-checklist"><h3>Shop launch checks</h3><p>{readiness.onlinePayments ? '✓ Online payment provider configured' : '○ Online payment provider needs configuration for online collection'}</p><p>{configuration.policy.customerEmail || configuration.policy.customerWhatsapp ? '✓ Customer reminders enabled — check a real delivery in reminder history' : '○ Customer email / WhatsApp reminders are currently off'}</p><p>{configuration.policy.requireConditionPhotos ? '✓ Condition photos required at handover and return' : '○ Condition photos are optional under the current policy'}</p><p>{configuration.policy.requireCustomerAcknowledgement ? '✓ Customer acknowledgement required' : '○ Customer acknowledgement is optional under the current policy'}</p><p>Studio tools: refund desk {configuration.policy.refundDashboardEnabled ? 'on' : 'off'} · piece reports {configuration.policy.piecePerformanceEnabled ? 'on' : 'off'} · waitlist {configuration.policy.waitlistEnabled ? 'on' : 'off'}.</p><p className="rental-muted">Configure reminder providers and customer consent before enabling sends. Check a booking, payment, pickup, return and refund on the deployed service before launch.</p><button type="button" className="rental-text-button" disabled={busy} onClick={() => onTab('settings')}>Open rental policy & reminder settings →</button></aside>
  </section>;
}
