import { blankRentalAddress, rentalAddressFields } from '../../utils/rentalDetails';
const labels = { STORE_PICKUP: 'Pick up at the store', SELF_DELIVERY: 'Store delivery & collection', COURIER: 'Courier delivery & return' };
export function RentalDateFields({ form, policy, onChange }) {
  return <><h2>When will you use it?</h2><div className="rental-checkout-fields"><label>Use day / occasion date<input type="date" value={form.useStart} onChange={e => onChange('useStart', e.target.value)} /></label>{(form.additionalUseDates || []).map((day, index) => <label key={index}>Additional use day {index + 1}<input type="date" value={day} onChange={e => onChange('additionalUseDates', form.additionalUseDates.map((old, i) => i === index ? e.target.value : old))} /><button type="button" className="rental-shopping-link" onClick={() => onChange('additionalUseDates', form.additionalUseDates.filter((_, i) => i !== index))}>Remove use day</button></label>)}</div><button type="button" className="rental-shopping-link" disabled={(form.additionalUseDates || []).length >= 89} onClick={() => onChange('additionalUseDates', [...(form.additionalUseDates || []), ''])}>+ Add another use day</button><p className="rental-shopping-hint">Rent is charged for these use days. Extra pickup and return days add no rent.</p><h3>Pickup & return</h3><div className="rental-checkout-fields"><label>Pickup date & time<input type="datetime-local" step={(policy.slotMinutes || 60) * 60} value={form.pickupAt} onChange={e => onChange('pickupAt', e.target.value)} /></label><label>Return date & time<input type="datetime-local" step={(policy.slotMinutes || 60) * 60} value={form.returnDueAt} onChange={e => onChange('returnDueAt', e.target.value)} /></label></div><p className="rental-shopping-hint">Shop timings: {policy.pickupStart}–{policy.pickupEnd}. Dates use {policy.timezone}. Availability is checked for the complete pickup-to-return period.</p><label className="rental-checkout-field">Receive your rental<select value={form.deliveryMode} onChange={e => onChange('deliveryMode', e.target.value)}>{policy.deliveryModes.map(mode => <option key={mode} value={mode}>{labels[mode] || mode}</option>)}</select></label></>;
}
export function RentalContactFields({ form, details, addresses, onChange, onDetails }) {
  const update = (key, value) => onDetails({ ...details, deliveryAddress: { ...details.deliveryAddress, [key]: value } });
  return <><h2>Contact & address</h2><div className="rental-checkout-fields"><label>Booking name<input autoComplete="name" value={form.name} maxLength={100} onChange={e => onChange('name', e.target.value)} /></label><label>Verified mobile<input value={form.phone} disabled /></label><label>Email for updates (optional)<input type="email" autoComplete="email" value={form.email} onChange={e => onChange('email', e.target.value)} /></label></div>{form.deliveryMode === 'STORE_PICKUP' ? <p className="rental-shopping-hint">Collect and return at the shop. No delivery address is needed.</p> : <><h3>Delivery & return address</h3>{addresses.length > 0 && <label className="rental-checkout-field">Use a saved address<select defaultValue="" onChange={e => { const address = addresses.find(row => row._id === e.target.value); if (address) onDetails({ ...details, deliveryAddress: blankRentalAddress({ name: form.name, phone: form.phone }, address) }); }}><option value="">Enter or choose an address</option>{addresses.map(row => <option key={row._id} value={row._id}>{row.fullName} · {row.houseNo} {row.area}, {row.city}</option>)}</select></label>}<div className="rental-checkout-fields">{rentalAddressFields.map(([key, label]) => <label key={key}>{label}<input value={details.deliveryAddress?.[key] || ''} type={key === 'mobile' || key === 'pincode' ? 'tel' : 'text'} maxLength={key === 'pincode' ? 6 : key === 'mobile' ? 14 : 150} onChange={e => update(key, e.target.value)} /></label>)}</div><p className="rental-shopping-hint">Return collection uses this same address. Contact the store to arrange a different return address.</p></>}<label className="rental-shopping-check"><input type="checkbox" checked={form.whatsappConsent} onChange={e => onChange('whatsappConsent', e.target.checked)} />Send rental updates on WhatsApp (optional)</label></>;
}
