import RentalCheckoutSlot from './RentalCheckoutSlot';
import { localDateTime } from '../../utils/rentals';
import { blankRentalAddress, rentalAddressFields } from '../../utils/rentalDetails';
const labels = { STORE_PICKUP: 'Pick up at the store', SELF_DELIVERY: 'Store delivery & collection', COURIER: 'Courier delivery & return' };
export function RentalDateFields({ form, policy, onChange, storeSlug, onSlotStatus }) {
  const earliest = localDateTime(Date.now() + (policy.minimumLeadHours || 0) * 3600000, policy.timezone).slice(0, 10);
  return <><section className="rental-date-card sc-mobile-checkout__card"><h2>Occasion date</h2><div className="rental-checkout-fields"><label>Use day / occasion date<input type="date" min={earliest} value={form.useStart} onChange={e => onChange('useStart', e.target.value)} /></label>{(form.additionalUseDates || []).map((day, index) => <label key={index}>Additional use day {index + 1}<input type="date" min={earliest} value={day} onChange={e => onChange('additionalUseDates', form.additionalUseDates.map((old, i) => i === index ? e.target.value : old))} /><button type="button" className="rental-shopping-link" onClick={() => onChange('additionalUseDates', form.additionalUseDates.filter((_, i) => i !== index))}>Remove use day</button></label>)}</div><button type="button" className="rental-shopping-link" disabled={(form.additionalUseDates || []).length >= (policy.maximumDays || 90) - 1} onClick={() => onChange('additionalUseDates', [...(form.additionalUseDates || []), ''])}>+ Add another use day</button>
    <p className="rental-use-day-note">Pay for use days only. Pickup and return days add no rent.</p><details className="rental-day-explanation"><summary>How is a use day counted?</summary><p>Each selected date counts once, from 12:00 AM to 11:59 PM in {policy.timezone}. Only dates you select as use days are charged.</p></details></section>
    <section className="rental-date-card sc-mobile-checkout__card"><h2>Pickup & return</h2><RentalCheckoutSlot kind="pickup" value={form.pickupAt} policy={policy} storeSlug={storeSlug} onChange={value => onChange('pickupAt', value)} onStatus={status => onSlotStatus?.('pickup', status)} />
    <RentalCheckoutSlot kind="return" value={form.returnDueAt} policy={policy} storeSlug={storeSlug} onChange={value => onChange('returnDueAt', value)} onStatus={status => onSlotStatus?.('return', status)} />
    <p className="rental-shopping-hint">Shop hours: {policy.pickupStart}–{policy.pickupEnd}. Times follow the shop's time zone. Item availability is confirmed in the next step.</p>
    {policy.deliveryModes.length > 1 && <label className="rental-checkout-field">Receive your rental<select value={form.deliveryMode} onChange={e => onChange('deliveryMode', e.target.value)}>{policy.deliveryModes.map(mode => <option key={mode} value={mode}>{labels[mode] || mode}</option>)}</select></label>}
    </section></>;
}
export function RentalContactFields({ form, details, addresses, onChange, onDetails, phoneControl }) {
  const update = (key, value) => onDetails({ ...details, deliveryAddress: { ...details.deliveryAddress, [key]: value } });
  return <><div className="rental-checkout-fields"><label>Full name<input autoComplete="name" value={form.name} maxLength={100} onChange={e => onChange('name', e.target.value)} /></label>{phoneControl || <label>Verified mobile<input value={form.phone} disabled /></label>}</div>{form.deliveryMode === 'STORE_PICKUP' ? <p className="rental-shopping-hint">Collect and return at the shop. No delivery address is needed.</p> : <><h3>Delivery & return address</h3>{addresses.length > 0 && <label className="rental-checkout-field">Use a saved address<select defaultValue="" onChange={e => { const address = addresses.find(row => row._id === e.target.value); if (address) onDetails({ ...details, deliveryAddress: blankRentalAddress({ name: form.name, phone: form.phone }, address) }); }}><option value="">Enter or choose an address</option>{addresses.map(row => <option key={row._id} value={row._id}>{row.fullName} · {row.houseNo} {row.area}, {row.city}</option>)}</select></label>}<div className="rental-checkout-fields">{rentalAddressFields.map(([key, label]) => <label key={key}>{label}<input value={details.deliveryAddress?.[key] || ''} type={key === 'mobile' || key === 'pincode' ? 'tel' : 'text'} maxLength={key === 'pincode' ? 6 : key === 'mobile' ? 14 : 150} onChange={e => update(key, e.target.value)} /></label>)}</div><p className="rental-shopping-hint">Return collection uses this same address. Contact the store to arrange a different return address.</p></>}<details className="rental-contact-optional"><summary>Email & WhatsApp updates (optional)</summary><div className="rental-checkout-fields"><label>Email for updates (optional)<input type="email" autoComplete="email" value={form.email} onChange={e => onChange('email', e.target.value)} /></label></div><label className="rental-shopping-check"><input type="checkbox" checked={form.whatsappConsent} onChange={e => onChange('whatsappConsent', e.target.checked)} />Send rental updates on WhatsApp (optional)</label></details></>;
}
