import { useEffect, useMemo, useState } from 'react';
import { Check, Clock3, FileText, Package, CalendarDays, ArrowRight } from 'lucide-react';
import { rentalUseDayLabel } from '../../utils/rentalShopping';
import { rentalCopy } from '../../utils/rentalCopy';
import { rentalDate, rentalMoney } from '../../utils/rentals';
import { responsiveImage } from '../../utils/responsiveImages';
import RentalDocuments from './RentalDocuments';
import RentalBookingDetails from './RentalBookingDetails';
import RentalProofPanel from './RentalProofPanel';
import RentalContact from './RentalContact';

const progress = ['Booked', 'Ready for you', 'With you', 'Returned'];
const stage = { CONFIRMED: 0, PREPARING: 0, READY: 1, OUT: 2, RETURNED: 3, CLOSED: 3 };
export default function RentalCustomerBooking({ booking, checkedAt, clockNow, busy, methods, method, setMethod, methodError, methodsLoading, loadMethods, pay, request, setRequest, sendRequest, contact, storeSlug, navigate, onChange, success = false }) {
  const [documents, setDocuments] = useState(false), [help, setHelp] = useState(false);
  const b = booking, finance = b.financial || {}, tz = b.policy.timezone;
  const expired = b.status === 'EXPIRED' || (b.status === 'HELD' && +new Date(b.expiresAt) <= clockNow);
  const cancelled = b.status === 'CANCELLED' || (b.status === 'CLOSED' && ['CANCELLED', 'EXPIRED'].includes(b.closedFromStatus));
  const held = b.status === 'HELD' && !expired;
  const title = expired ? 'Booking hold expired' : cancelled ? 'Booking cancelled' : held ? 'Complete your booking' : success ? 'Your rental is booked!' : b.number;
  const canPay = !expired && !cancelled && finance.balancePaise > 0 && ['HELD', 'CONFIRMED', 'PREPARING', 'READY', 'OUT', 'RETURNED'].includes(b.status);
  const canCancel = !expired && ['HELD', 'CONFIRMED', 'PREPARING', 'READY'].includes(b.status);
  const cancelPending = b.requests?.some(row => row.type === 'CANCEL' && row.status === 'PENDING');
  const requestTypes = useMemo(() => [...(['OUT'].includes(b.status) ? ['RETURN_COLLECTION', 'EXTEND'] : !expired && ['HELD', 'CONFIRMED', 'PREPARING', 'READY'].includes(b.status) ? ['RESCHEDULE', ...(!cancelPending ? ['CANCEL'] : [])] : []), 'DISPUTE'], [b.status, expired, cancelPending]);
  useEffect(() => { if (!requestTypes.includes(request.type)) { setRequest(old => ({ ...old, type: requestTypes[0], pickupAt: '', returnDueAt: '' })); setHelp(false); } }, [requestTypes, request.type, setRequest]);
  const due = held ? Math.max(0, b.quote.dueNowPaise - (finance.collectedPaise || 0)) : finance.balancePaise;
  return <div className="rental-customer-booking"><section className="rental-shopping-card rental-booking-confirmation"><span className={'rental-booking-confirmation__icon' + (held || expired ? ' is-pending' : '')}>{held || expired ? <Clock3 size={29} /> : <Check size={29} />}</span><div><p className="rental-shopping-eyebrow">{title === b.number ? 'RENTAL BOOKING' : b.number}</p><h1>{title}</h1><p>{expired ? 'Choose dates again to check the latest availability.' : cancelled ? 'Your cancellation and any approved refund are recorded below.' : held ? 'Your items are held temporarily. Pay before the hold expires to confirm.' : b.quote.paymentPlan === 'PICKUP' ? 'Your dates are reserved. Pay rent and security at pickup.' : 'Your booking is confirmed. Follow pickup and return updates here.'}</p>{checkedAt && <small>Updated {new Date(checkedAt).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}</small>}</div></section>
    {!held && !expired && !cancelled && <ol className="rental-booking-progress" aria-label="Booking progress">{progress.map((label, i) => <li key={label} className={(stage[b.status] ?? -1) >= i ? 'is-done' : ''} aria-current={stage[b.status] === i ? 'step' : undefined}><span>{(stage[b.status] ?? -1) >= i ? <Check size={15} /> : i + 1}</span>{label}</li>)}</ol>}
    <div className="rental-shopping-columns"><div className="rental-booking-main"><section className="rental-shopping-card"><h2>Your booked items</h2>{b.quote.items.map(item => { const image = responsiveImage(item.image, 'thumbnail'); return <article className="rental-booked-item" key={item.listingId}>{image.src ? <img {...image} alt="" /> : <span className="rental-booked-item__placeholder"><Package size={27} /></span>}<div><h3>{item.title}</h3><p>Quantity {item.quantity} · {b.schedule.days} {b.schedule.billingBasis === 'USE_DAYS' ? b.schedule.days === 1 ? 'use day' : 'use days' : b.schedule.days === 1 ? 'rental day' : 'rental days'}</p><strong>{rentalMoney(item.rentPaise)}</strong></div></article>; })}</section>
      <section className="rental-shopping-card"><h2><CalendarDays size={18} />Dates & collection</h2>{b.schedule.useDates?.length > 0 && <p><strong>Use days</strong> · {b.schedule.useDates.map(rentalUseDayLabel).join(', ')}</p>}<div className="rental-booking-dates"><div><small>Pickup / delivery</small><strong>{rentalDate(b.schedule.pickupAt, tz)}</strong></div><div><small>Return by</small><strong>{rentalDate(b.schedule.returnDueAt, tz)}</strong></div></div><p>{b.quote.deliveryMode === 'STORE_PICKUP' ? 'Collect and return at the store.' : b.logistics?.address}</p>{['outbound', 'inbound'].map(direction => { const leg = b.logistics?.[direction]; return leg?.trackingId || leg?.trackingUrl ? <p key={direction}>{direction === 'outbound' ? 'Delivery' : 'Return'} · {leg.carrier} {leg.trackingId}{leg.trackingUrl && <a href={leg.trackingUrl} target="_blank" rel="noopener noreferrer">Track parcel →</a>}</p> : null; })}{b.overdue && <p role="alert">Your return is overdue. Contact the store to arrange return.</p>}</section>
      <section className="rental-shopping-card rental-booking-actions"><button type="button" className="rental-shopping-secondary" aria-expanded={documents} onClick={() => setDocuments(v => !v)}><FileText size={18} />Invoice & receipts</button><button type="button" className="rental-shopping-secondary" aria-expanded={help} onClick={() => { setHelp(v => !v); setRequest({ type: requestTypes[0], note: '', pickupAt: '', returnDueAt: '' }); }}>Change dates / get help</button>{canCancel && <button type="button" className="rental-shopping-link" disabled={busy || cancelPending} onClick={() => { setHelp(true); setRequest({ type: 'CANCEL', note: '', pickupAt: '', returnDueAt: '' }); }}>{cancelPending ? 'Cancellation under review' : 'Cancel booking'}</button>}</section>
      {documents && <RentalDocuments booking={b} />}
      {help && <section className="rental-shopping-card"><h2>{request.type === 'CANCEL' ? 'Request cancellation' : 'Ask the store'}</h2>{request.type === 'CANCEL' && <p>Cancellation and refund are reviewed by the admin. The approved refund may be full, partial or zero; the decision and refund status appear here.</p>}<fieldset disabled={busy} className="rental-checkout-fieldset"><label className="rental-checkout-field">Request<select value={request.type} onChange={e => setRequest(old => ({ ...old, type: e.target.value }))}>{requestTypes.map(type => <option key={type} value={type}>{rentalCopy(type)}</option>)}</select></label>{request.type === 'RESCHEDULE' && <label className="rental-checkout-field">Requested pickup<input type="datetime-local" value={request.pickupAt} onChange={e => setRequest(old => ({ ...old, pickupAt: e.target.value }))} /></label>}{['EXTEND', 'RESCHEDULE'].includes(request.type) && <label className="rental-checkout-field">Requested return<input type="datetime-local" value={request.returnDueAt} onChange={e => setRequest(old => ({ ...old, returnDueAt: e.target.value }))} /></label>}<label className="rental-checkout-field">{request.type === 'CANCEL' ? 'Reason for cancellation' : 'Your message'}<textarea value={request.note} maxLength={1000} onChange={e => setRequest(old => ({ ...old, note: e.target.value }))} /></label><button type="button" className="rental-shopping-primary" disabled={!request.note.trim() || busy || !requestTypes.includes(request.type)} onClick={sendRequest}>{request.type === 'CANCEL' ? 'Submit cancellation request' : 'Send request'}</button></fieldset></section>}
      {!!b.requests?.length && <section className="rental-shopping-card"><h2>Your requests</h2>{b.requests.map(row => <div className="rental-booking-request" key={row.operationId}><strong>{rentalCopy(row.type)} · {rentalCopy(row.status)}</strong><p>{row.note}</p>{row.responseNote && <p>Store reply: {row.responseNote}</p>}</div>)}</section>}
      <details className="rental-shopping-card"><summary>Booking details & history</summary><RentalBookingDetails booking={b} /><ol className="rental-timeline">{(b.events || []).map((event, i) => <li key={i}><strong>{rentalCopy(event.type)}</strong><time>{rentalDate(event.at, tz)}</time><p>{event.note}</p></li>)}</ol><p>{b.policy.terms}</p>{(b.assessments || []).map(row => <p key={row.operationId}>{row.approved ? 'Approved' : 'Waived'} charge · {row.reason} · {rentalMoney(row.amountPaise)}</p>)}</details>
      {(b.policy.requireConditionPhotos || b.policy.requireCustomerAcknowledgement || ['OUT', 'RETURNED'].includes(b.status)) && <details className="rental-shopping-card"><summary>Pickup / return photos & acknowledgement</summary><RentalProofPanel key={storeSlug + ':' + b._id} base="/rentals" storeSlug={storeSlug} booking={b} onChange={onChange} /></details>}
      {b.trial?.at && <section className="rental-shopping-card"><h2>Fitting appointment</h2><p>{rentalDate(b.trial.at, tz)} · {rentalCopy(b.trial.status)}</p><p>{b.trial.notes}</p></section>}
    </div><aside className="rental-shopping-card rental-booking-payment"><h2>Payment summary</h2>{[['Rent & services', b.adjustedRentalPaise ?? b.quote.rentalPaise], ['Refundable security', b.quote.depositPaise], ['Paid', finance.collectedPaise], ['Remaining', finance.balancePaise], ['Refund processed', finance.refundedPaise]].map(([label, amount]) => <div className="rental-price-row" key={label}><span>{label}</span><strong>{rentalMoney(amount)}</strong></div>)}{cancelled || ['RETURNED', 'CLOSED'].includes(b.status) ? <><div className="rental-price-row"><span>Approved refund available</span><strong>{rentalMoney(finance.refundablePaise)}</strong></div>{finance.reservedRefundPaise > finance.refundedPaise && <p>Refund processing: {rentalMoney(finance.reservedRefundPaise - finance.refundedPaise)}</p>}</> : b.quote.paymentPlan === 'PICKUP' && <p>Payment is due at pickup before handover. You may also pay online earlier if offered below.</p>}
      {held && <p role="status" className="rental-shopping-notice">Pay before {rentalDate(b.expiresAt, tz)} to confirm this booking.</p>}{canPay && <>{methodsLoading && <p role="status">Loading payment options…</p>}{methodError && <div><p role="alert">{methodError}</p><button type="button" disabled={busy || methodsLoading} onClick={loadMethods}>Retry payment options</button></div>}{methods.length > 0 && <label className="rental-checkout-field">Online payment method<select value={method} onChange={e => setMethod(e.target.value)}>{methods.map(row => <option key={row.key} value={row.key}>{row.label}</option>)}</select></label>}{method && <button type="button" className="rental-shopping-primary" disabled={busy} onClick={pay}>{busy ? 'Opening payment…' : 'Pay ' + rentalMoney(due)}</button>}{!methods.length && <RentalContact contact={contact} navigate={navigate} message="Contact store for payment. Your booking payment arrangement is shown above." />}</>}
      <RentalContact contact={contact} navigate={navigate} message="Need help with this booking? Contact the store." /><button className="rental-shopping-link" type="button" onClick={() => navigate('/rental-book')}>Browse more rentals<ArrowRight size={16} /></button>
    </aside></div>
  </div>;
}
