import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import '@testing-library/jest-dom';
import RentalBookingForm from './RentalBookingForm';
import api from '../../services/api';
jest.mock('../../services/api', () => ({ post: jest.fn() }));
beforeEach(() => sessionStorage.clear());
const configuration = { policy: { timezone: 'Asia/Kolkata', slotMinutes: 60, deliveryModes: ['STORE_PICKUP'] } };
const listing = { _id: 'list1', productId: 'prod1', title: 'Bridal lehenga M', dailyRatePaise: 100000, depositPaise: 500000, packages: [] };
test('booking needs a reviewed quote and terms; dates sent with explicit timezone', async () => {
  const onBooked = jest.fn(); api.post.mockResolvedValueOnce({ quoteFingerprint: 'reviewed_price', policyRevision: 3, timezone: 'Asia/Kolkata', terms: 'Return by noon.', schedule: { pickupAt: '2030-01-10T04:30Z', returnDueAt: '2030-01-12T04:30Z' }, quote: { rentalPaise: 200000, depositPaise: 500000, dueNowPaise: 560000 } }).mockResolvedValueOnce({ _id: 'booking1' });
  render(<RentalBookingForm listings={[listing]} configuration={configuration} user={{ _id: 'buyer', isPhoneVerified: true, name: 'Buyer', phone: '9000000001' }} onBooked={onBooked} />);
  fireEvent.click(screen.getByLabelText('Select Bridal lehenga M'));
  fireEvent.change(screen.getByLabelText('Pickup / delivery time'), { target: { value: '2030-01-10T10:00' } });
  fireEvent.change(screen.getByLabelText('Return deadline'), { target: { value: '2030-01-12T10:00' } });
  fireEvent.click(screen.getByRole('button', { name: 'Continue to items' }));
  fireEvent.click(screen.getByRole('button', { name: 'Check dates & review price' }));
  fireEvent.click(await screen.findByRole('button', { name: 'Continue to review & pay' }));
  const reserve = await screen.findByRole('button', { name: 'Reserve rental' }); expect(reserve).toBeDisabled();
  fireEvent.click(screen.getByLabelText(/I accept these rental terms/)); fireEvent.click(reserve);
  await waitFor(() => expect(onBooked).toHaveBeenCalledWith({ _id: 'booking1' }));
  expect(api.post.mock.calls[1][1]).toEqual(expect.objectContaining({ pickupAt: '2030-01-10T04:30:00.000Z', policyRevision: 3, quoteFingerprint: 'reviewed_price', acceptTerms: true }));
});

test('a changed quote clears acceptance and requires another review instead of silently booking', async () => {
  api.post.mockReset();
  api.post.mockResolvedValueOnce({ quoteFingerprint: 'old_price', policyRevision: 1, terms: 'Accepted terms', schedule: {}, quote: { rentalPaise: 200000, depositPaise: 500000, dueNowPaise: 560000 } });
  api.post.mockRejectedValueOnce(Object.assign(new Error('Review the new price.'), { code: 'RENTAL_QUOTE_CHANGED' }));
  const onBooked = jest.fn();
  render(<RentalBookingForm listings={[listing]} configuration={configuration} user={{ _id: 'buyer', isPhoneVerified: true, name: 'Buyer', phone: '9000000001' }} onBooked={onBooked} />);
  fireEvent.click(screen.getByLabelText('Select Bridal lehenga M'));
  fireEvent.change(screen.getByLabelText('Pickup / delivery time'), { target: { value: '2030-01-10T10:00' } });
  fireEvent.change(screen.getByLabelText('Return deadline'), { target: { value: '2030-01-12T10:00' } });
  fireEvent.click(screen.getByRole('button', { name: 'Continue to items' }));
  fireEvent.click(screen.getByRole('button', { name: 'Check dates & review price' }));
  fireEvent.click(await screen.findByRole('button', { name: 'Continue to review & pay' }));
  fireEvent.click(await screen.findByLabelText(/I accept these rental terms/));
  fireEvent.click(screen.getByRole('button', { name: 'Reserve rental' }));
  expect(await screen.findByRole('alert')).toHaveTextContent('Review the new price.');
  expect(screen.queryByRole('button', { name: 'Reserve rental' })).not.toBeInTheDocument(); expect(onBooked).not.toHaveBeenCalled();
});

test('anonymous customer plans and reviews before OTP, and keeps the selected plan', async () => {
  api.post.mockReset(); const onRequireLogin = jest.fn();
  api.post.mockResolvedValue({ quoteFingerprint: 'plan', policyRevision: 1, terms: 'Terms', schedule: {}, quote: { rentalPaise: 100000, depositPaise: 200000, dueNowPaise: 30000 } });
  render(<RentalBookingForm storeSlug="bridal" listings={[listing]} initialItems={[{ listingId: 'list1', quantity: 1 }]} configuration={configuration} user={null} onRequireLogin={onRequireLogin} />);
  fireEvent.change(screen.getByLabelText('Pickup / delivery time'), { target: { value: '2030-01-10T10:00' } });
  fireEvent.change(screen.getByLabelText('Return deadline'), { target: { value: '2030-01-12T10:00' } });
  fireEvent.click(screen.getByRole('button', { name: 'Continue to items' }));
  expect(screen.getByLabelText('Select Bridal lehenga M')).toBeChecked();
  fireEvent.click(screen.getByRole('button', { name: 'Check dates & review price' }));
  await screen.findByRole('button', { name: 'Sign in with OTP to reserve' });
  expect(screen.queryByLabelText('Booking name')).not.toBeInTheDocument();
  expect(screen.queryByLabelText('Email')).not.toBeInTheDocument();
  fireEvent.click(screen.getByLabelText(/I accept these rental terms/));
  fireEvent.click(screen.getByRole('button', { name: 'Sign in with OTP to reserve' }));
  expect(onRequireLogin).toHaveBeenCalledTimes(1); expect(api.post).toHaveBeenCalledTimes(1);
  const values = Object.keys(sessionStorage).map(key => JSON.parse(sessionStorage.getItem(key)));
  expect(values.some(value => value.items?.[0]?.listingId === 'list1')).toBe(true);
});
test('an uncertain reservation cannot create another hold; recovery sends the same accepted attempt', async () => {
  api.post.mockReset(); const onBooked = jest.fn();
  api.post.mockResolvedValueOnce({ quoteFingerprint: 'accepted', policyRevision: 1, terms: 'Terms', schedule: {}, quote: { rentalPaise: 100000, depositPaise: 200000, dueNowPaise: 30000 } });
  api.post.mockRejectedValueOnce(new Error('Connection interrupted'));
  api.post.mockResolvedValueOnce({ _id: 'recovered' });
  render(<RentalBookingForm listings={[listing]} configuration={configuration} initialItems={[{ listingId: 'list1', quantity: 1 }]} user={{ _id: 'buyer', isPhoneVerified: true, name: 'Buyer', phone: '9000000001' }} onBooked={onBooked} />);
  fireEvent.change(screen.getByLabelText('Pickup / delivery time'), { target: { value: '2030-01-10T10:00' } });
  fireEvent.change(screen.getByLabelText('Return deadline'), { target: { value: '2030-01-12T10:00' } });
  fireEvent.click(screen.getByRole('button', { name: 'Continue to items' }));
  fireEvent.click(screen.getByRole('button', { name: 'Check dates & review price' }));
  fireEvent.click(await screen.findByRole('button', { name: 'Continue to review & pay' }));
  fireEvent.click(screen.getByLabelText(/I accept these rental terms/));
  fireEvent.click(screen.getByRole('button', { name: 'Reserve rental' }));
  expect(await screen.findByRole('alert')).toHaveTextContent('Connection interrupted');
  fireEvent.click(screen.getByRole('button', { name: 'Reserve rental' }));
  expect(api.post).toHaveBeenCalledTimes(2);
  fireEvent.click(screen.getByRole('button', { name: 'Retry same reservation' }));
  await waitFor(() => expect(onBooked).toHaveBeenCalledWith({ _id: 'recovered' }));
  expect(api.post.mock.calls[2][1]).toEqual(api.post.mock.calls[1][1]);
});

test('linked dates open items directly; editing dates manually keeps the date step open', () => {
  const first = render(<RentalBookingForm listings={[listing]} configuration={configuration} user={null} initialSchedule={{ pickupAt: '2030-01-10T10:00', returnDueAt: '2030-01-12T10:00' }} />);
  expect(screen.getByRole('button', { name: 'Check dates & review price' })).toBeVisible();
  first.unmount();
  render(<RentalBookingForm listings={[listing]} configuration={configuration} user={null} />);
  fireEvent.change(screen.getByLabelText('Pickup / delivery time'), { target: { value: '2030-01-10T10:00' } });
  fireEvent.change(screen.getByLabelText('Return deadline'), { target: { value: '2030-01-12T10:00' } });
  expect(screen.getByRole('button', { name: 'Continue to items' })).toBeVisible();
});
test('reload restores authenticated booking details and requires a fresh quote and terms', async () => {
  api.post.mockReset();
  const user = { _id: 'buyer', isPhoneVerified: true, name: 'Buyer', phone: '9876543210', email: 'account@example.test' };
  const props = { listings: [listing], configuration, user, storeSlug: 'bridal', initialItems: [{ listingId: 'list1', quantity: 1 }], initialSchedule: { pickupAt: '2030-01-10T10:00', returnDueAt: '2030-01-12T10:00' } };
  api.post.mockResolvedValue({ timezone: 'Asia/Kolkata', policyRevision: 1, quoteFingerprint: 'fresh', terms: 'Fresh terms', schedule: {}, quote: { rentalPaise: 100000, depositPaise: 0, advanceRentPaise: 30000, dueNowPaise: 30000 } });
  const first = render(<RentalBookingForm {...props} />);
  fireEvent.click(screen.getByRole('button', { name: 'Check dates & review price' }));
  await screen.findByRole('button', { name: 'Continue to review & pay' });
  fireEvent.change(screen.getByLabelText('Customer name'), { target: { value: 'Wedding booking name' } });
  fireEvent.change(screen.getByLabelText('Email for booking updates (optional)'), { target: { value: 'booking@example.test' } });
  fireEvent.change(screen.getByLabelText('Special fitting instructions (optional)'), { target: { value: 'Please confirm the blouse adjustment.' } });
  first.unmount();
  render(<RentalBookingForm {...props} />);
  expect(screen.getByLabelText('Customer name')).toHaveValue('Wedding booking name');
  expect(screen.getByLabelText('Email for booking updates (optional)')).toHaveValue('booking@example.test');
  expect(screen.getByLabelText('Special fitting instructions (optional)')).toHaveValue('Please confirm the blouse adjustment.');
  expect(screen.queryByRole('button', { name: 'Reserve rental' })).not.toBeInTheDocument();
  expect(screen.queryByLabelText(/I accept these rental terms/)).not.toBeInTheDocument();
  fireEvent.click(screen.getByRole('button', { name: 'Check dates & review price' }));
  fireEvent.click(await screen.findByRole('button', { name: 'Continue to review & pay' }));
  expect(screen.getByRole('button', { name: 'Reserve rental' })).toBeDisabled();
  expect(api.post).toHaveBeenCalledTimes(2);
});
test('account changes do not expose or overwrite the previous account contact draft', () => {
  const firstUser = { _id: 'one', isPhoneVerified: true, name: 'First', phone: '9876543210' };
  const props = { listings: [listing], configuration, storeSlug: 'bridal' };
  const view = render(<RentalBookingForm {...props} user={firstUser} />);
  fireEvent.change(screen.getByLabelText('Customer name'), { target: { value: 'First private booking name' } });
  view.rerender(<RentalBookingForm {...props} user={{ ...firstUser, _id: 'two', name: 'Second' }} />);
  expect(screen.getByLabelText('Customer name')).toHaveValue('Second');
  const draft = JSON.parse(sessionStorage.getItem('rental-contact:bridal:one'));
  expect(draft.customer.name).toBe('First private booking name');
  expect(JSON.parse(sessionStorage.getItem('rental-contact:bridal:two')).customer.name).toBe('Second');
  view.rerender(<RentalBookingForm {...props} user={null} />);
  expect(screen.queryByLabelText('Customer name')).not.toBeInTheDocument();
});
