import { useEffect, useState } from 'react';
import api from '../../services/api';
import { localDateTime, rentalDate, rentalInstant } from '../../utils/rentals';
import { RentalField, RentalStatus } from './RentalUi';
const priority = ['OVERDUE', 'OVERDUE_TASK', 'SOLD', 'LOST', 'RETIRED', 'REPAIR', 'INSPECTION', 'OUT', 'TASK', 'MAINTENANCE', 'TRIAL', 'HELD', 'BOOKED', 'CLEANING', 'CLEANING_BUFFER', 'PREPARATION'];
export default function RentalPieceTimeline({ base, timezone, refresh = 0, onOpen }) {
  const [start, setStart] = useState(localDateTime(new Date(), timezone).slice(0, 10)), [days, setDays] = useState(7), [search, setSearch] = useState(''), [query, setQuery] = useState(''), [page, setPage] = useState(1), [reload, setReload] = useState(0);
  const [data, setData] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState('');
  useEffect(() => {
    let alive = true; setBusy(true); setError('');
    api.get(`${base}/timeline?${new URLSearchParams({ start, days: String(days), page: String(page), search: query })}`, { silent: true, forceRefetch: true }).then(value => { if (!Array.isArray(value?.rows) || !Array.isArray(value?.dates)) throw new Error('Piece timeline could not be loaded. Refresh to retry.'); if (alive) setData(value); }).catch(e => { if (alive) setError(e.details || e.message); }).finally(() => { if (alive) setBusy(false); });
    return () => { alive = false; };
  }, [base, start, days, page, query, reload, refresh]);
  useEffect(() => { const update = () => { if (document.visibilityState !== 'hidden') setReload(v => v + 1); }; const timer = setInterval(update, 60000); window.addEventListener('focus', update); return () => { clearInterval(timer); window.removeEventListener('focus', update); }; }, []);
  const daySegments = (row, date) => {
    const next = new Date(Date.parse(`${date}T12:00Z`) + 86400000).toISOString().slice(0, 10), from = +new Date(rentalInstant(`${date}T00:00`, timezone)), to = +new Date(rentalInstant(`${next}T00:00`, timezone));
    return row.segments.filter(s => +new Date(s.from) < to && +new Date(s.to) > from).sort((a, b) => priority.indexOf(a.kind) - priority.indexOf(b.kind));
  };
  return <section className="rental-card rental-piece-timeline" aria-busy={busy}><span className="rental-eyebrow">PHYSICAL INVENTORY</span><h2>Piece planning calendar</h2><form className="rental-fields" onSubmit={e => { e.preventDefault(); setQuery(search.trim()); setPage(1); }}><RentalField label="Timeline starts" type="date" value={start} onChange={value => { setStart(value); setPage(1); }} /><RentalField label="Timeline view"><select value={days} onChange={e => { setDays(Number(e.target.value)); setPage(1); }}><option value="7">Week · 7 days</option><option value="31">Month · 31 days</option></select></RentalField><RentalField label="Find piece code, label or pool" value={search} maxLength={100} onChange={setSearch} /><button type="submit" className="rental-button">Find pieces</button><button type="button" className="rental-button rental-button--secondary" disabled={busy} onClick={() => setReload(v => v + 1)}>Refresh timeline</button></form>
    <div className="rental-timeline-legend">{['BOOKED', 'OUT', 'OVERDUE', 'PREPARATION', 'CLEANING', 'REPAIR', 'MAINTENANCE', 'TRIAL'].map(kind => <span key={kind} className={`rental-timeline-chip rental-timeline-chip--${kind.toLowerCase()}`}>{kind.replace(/_/g, ' ')}</span>)}</div>
    {error && <p role="alert" className="rental-notice">{error}</p>}{busy && <p role="status">Loading piece calendar…</p>}
    {data && !busy && !error && <><p className="rental-muted">{data.note} Times use {data.timezone}. Checked {rentalDate(data.checkedAt, timezone)}.</p><div className="rental-table-wrap"><table className="rental-table rental-timeline-table"><thead><tr><th>Piece</th>{data.dates.map(date => <th key={date}>{new Intl.DateTimeFormat('en-IN', { weekday: 'short', day: 'numeric', month: 'short', timeZone: 'UTC' }).format(new Date(`${date}T12:00Z`))}</th>)}</tr></thead><tbody>{data.rows.map(row => <tr key={row._id}><th scope="row"><strong>{row.code}</strong><br />{row.label}<br /><RentalStatus value={row.status} /></th>{data.dates.map(date => { const segments = daySegments(row, date); return <td key={date} aria-label={`${row.code} ${date}: ${segments.length ? segments.map(s => s.kind).join(', ') : 'No scheduled block'}`}>{segments.length ? segments.map((s, i) => <button type="button" key={i} disabled={!s.bookingId} className={`rental-timeline-chip rental-timeline-chip--${s.kind.toLowerCase()}`} title={`${s.number || ''} ${rentalDate(s.from, timezone)} → ${rentalDate(s.to, timezone)}${s.needsRelease ? ' · staff release required' : ''}`} onClick={() => s.bookingId && onOpen(s.bookingId)}>{s.kind.replace(/_/g, ' ')}{s.number && <small>{s.number}</small>}</button>) : <span className="rental-timeline-free">No block</span>}</td>; })}</tr>)}</tbody></table>{!data.rows.length && <p>No physical pieces match this search.</p>}</div><div className="rental-actions"><button type="button" className="rental-button rental-button--secondary" disabled={page <= 1} onClick={() => setPage(p => p - 1)}>Previous pieces</button><span>{data.total} pieces · page {data.page}</span><button type="button" className="rental-button rental-button--secondary" disabled={page >= data.pages} onClick={() => setPage(p => p + 1)}>Next pieces</button></div></>}
  </section>;
}
