import { useCallback, useEffect, useRef, useState } from 'react';
import api from '../../services/api';
import { announceSettingsSaved } from '../../config/storeSettings';
const KEYS = ['enabled', 'consentRequired', 'timezone', 'sessionTimeoutMinutes', 'rawRetentionDays', 'summaryRetentionDays', 'attributionDays', 'excludedPaths', 'excludedReferrers', 'excludeLocalhost', 'ga4Enabled', 'ga4MeasurementId'];
const editable = data => ({ ...Object.fromEntries(KEYS.map(key => [key, data[key]])), whatsappDigest: { enabled: data.whatsappDigest?.enabled || false, frequency: data.whatsappDigest?.frequency || 'DAILY', recipient: data.whatsappDigest?.recipient || '', consent: data.whatsappDigest?.consent || false, templateName: data.whatsappDigest?.templateName || '', language: data.whatsappDigest?.language || 'en' } });

export default function TrafficSettings({ apiBase = '/admin/settings', onDirtyChange, onBusyChange }) {
  const [data, setData] = useState(null); const [form, setForm] = useState(null); const [baseline, setBaseline] = useState(null);
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [retentionConfirmed, setRetentionConfirmed] = useState(false); const [confirmation, setConfirmation] = useState('');
  const [uncertainId, setUncertainId] = useState('');
  const lock = useRef(false); const dirty = !!form && JSON.stringify(form) !== JSON.stringify(baseline);
  useEffect(() => { onDirtyChange?.(dirty); }, [dirty, onDirtyChange]);
  useEffect(() => { onBusyChange?.(busy); }, [busy, onBusyChange]);
  useEffect(() => () => { onDirtyChange?.(false); onBusyChange?.(false); }, [onDirtyChange, onBusyChange]);
  const accept = value => { setData(value); setForm(editable(value)); setBaseline(editable(value)); setRetentionConfirmed(false); };
  const load = useCallback(async () => {
    setLoading(true); setError('');
    try { accept(await api.get(`${apiBase}/traffic`, { silent: true, cache: 'no-store' })); }
    catch (failure) { setError(failure.message); }
    finally { setLoading(false); }
  }, [apiBase]);
  useEffect(() => { load(); }, [load]);
  const run = async action => {
    if (lock.current) return; lock.current = true; setBusy(true); setError(''); setNotice('');
    try { await action(); }
    catch (failure) { setError(failure.message); }
    finally { lock.current = false; setBusy(false); }
  };
  const update = (key, value) => { setForm(current => ({ ...current, [key]: value })); setNotice(''); };
  const toggle = (key, label, note) => <label className="store-settings__toggle" key={key}><span><strong>{label}</strong>{note && <small>{note}</small>}</span><input type="checkbox" aria-label={label} checked={!!form[key]} onChange={event => update(key, event.target.checked)} /><i aria-hidden="true" /></label>;
  const number = (key, label, min, max) => <label className="store-settings__field" key={key}><span>{label}</span><input aria-label={label} type="number" min={min} max={max} step="1" value={form[key]} onChange={event => update(key, event.target.value)} /><small>{min}–{max}</small></label>;
  if (loading) return <p role="status">Loading traffic settings...</p>;
  if (!form) return <div role="alert"><p>{error || 'Traffic settings unavailable.'}</p><button type="button" className="admin-btn-ghost" onClick={load}>Retry settings</button></div>;
  const reducing = Number(form.rawRetentionDays) < baseline.rawRetentionDays || Number(form.summaryRetentionDays) < baseline.summaryRetentionDays;
  const digestField = (key, value) => update('whatsappDigest', { ...form.whatsappDigest, [key]: value });
  const retryDigest = (id, confirmUncertain = false) => run(async () => { await api.post(`${apiBase}/traffic/digests/${id}/retry`, { confirmUncertain }, { silent: true }); await load(); setNotice('Traffic digest queued for retry.'); });
  return <div className="space-y-5">
    <div className="store-settings__tip"><p>Measure anonymous visits without affecting cart, login or checkout. Traffic appears in <a href={apiBase.startsWith('/seller') ? '/seller/traffic' : '/admin/traffic'}>Traffic & visitors</a> and Reports & Insights. Admin/seller/master pages, previews and known bots are excluded. Visitor totals are estimates, not a directory of people.</p></div>
    {error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
    {notice && <p role="status" className="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">{notice}</p>}
    <fieldset disabled={busy} className="space-y-5">
      {toggle('enabled', 'Enable storefront traffic analytics', 'Turning this off stops new collection. Existing analytics and orders are not deleted.')}
      {toggle('consentRequired', 'Require explicit analytics consent', 'Recommended. Visitors can decline, withdraw consent and request deletion from Privacy preferences. GA4 always needs explicit consent.')}
      {toggle('excludeLocalhost', 'Exclude localhost development traffic', 'Prevents local browser sessions from polluting production reports.')}
      <div className="grid gap-4 sm:grid-cols-2"><label className="store-settings__field"><span>Traffic timezone</span><input aria-label="Traffic timezone" value={form.timezone} onChange={event => update('timezone', event.target.value)} placeholder="Asia/Kolkata" maxLength={60} /><small>Use an IANA timezone. “Today” starts at local midnight; timestamps remain UTC.</small></label>{number('sessionTimeoutMinutes', 'Visit inactivity timeout (minutes)', 5, 120)}{number('attributionDays', 'Campaign attribution window (days)', 1, 90)}{number('rawRetentionDays', 'Detailed event retention (days)', 7, 180)}{number('summaryRetentionDays', 'Compact traffic retention (days)', 30, 730)}</div>
      {reducing && <label className="flex items-start gap-3 rounded-xl bg-amber-50 p-4 text-sm text-amber-950"><input type="checkbox" checked={retentionConfirmed} onChange={event => setRetentionConfirmed(event.target.checked)} /><span>I understand that reducing retention permanently expires older analytics. Increasing it later cannot recover deleted data.</span></label>}
      <div className="grid gap-4 sm:grid-cols-2"><label className="store-settings__field"><span>Additional excluded paths</span><textarea aria-label="Additional excluded paths" rows="4" value={form.excludedPaths.join('\n')} onChange={event => update('excludedPaths', event.target.value.split('\n'))} placeholder={'/test\n/internal-preview'} /><small>One path prefix per line, up to 30. Excluding / excludes the entire storefront.</small></label><label className="store-settings__field"><span>Excluded referral hosts</span><textarea aria-label="Excluded referral hosts" rows="4" value={form.excludedReferrers.join('\n')} onChange={event => update('excludedReferrers', event.target.value.split('\n'))} placeholder="monitor.example.com" /><small>Exact hostnames only, not full URLs.</small></label></div>
      <section className="space-y-3 rounded-xl border border-theme-border p-4"><h3 className="font-bold">Optional Google Analytics 4</h3>{toggle('ga4Enabled', 'Enable this store’s GA4 integration', 'Not required for the built-in dashboard. Loads only after the visitor explicitly allows analytics.')}<label className="store-settings__field"><span>GA4 measurement ID</span><input aria-label="GA4 measurement ID" maxLength={22} value={form.ga4MeasurementId} onChange={event => update('ga4MeasurementId', event.target.value)} placeholder="G-XXXXXXXXXX" /></label><p className="text-sm text-theme-muted">Use a separate property for each client. In the GA4 web stream, turn off Enhanced measurement (automatic page/history, form and search tracking); this app sends only sanitized manual page views. Do not add a second tag in Website Designer. Ad personalization and Google signals are disabled by this integration. Update your published privacy policy for the providers you enable.</p></section>
      <section className="rounded-xl border border-theme-border p-4 text-sm"><h3 className="font-bold">Daily / weekly email digest</h3><p className="mt-2 text-theme-muted">Open Reports → Traffic & visitors, choose a rolling period, then Save view and select Daily or Weekly. Traffic CSV/PDF exports use the active filters. Email uses the backend’s configured Brevo transactional sender; schedules stay disabled until a recipient and provider are configured. Sending a report requires report-management/export permissions.</p></section>
      <section className="space-y-3 rounded-xl border border-theme-border p-4 text-sm"><h3 className="font-bold">Optional WhatsApp traffic digest</h3><p className="text-theme-muted">{data.whatsappProvider?.ready ? 'Encrypted Meta provider credentials are available.' : 'First configure Meta credentials and a secure storefront URL in Order alerts.'} Sends the previous complete day, or previous complete seven days, at 09:00 in the traffic timezone (weekly: Monday). No old periods are broadcast on activation.</p><label className="flex gap-3"><input type="checkbox" aria-label="Enable WhatsApp traffic digest" checked={form.whatsappDigest.enabled} onChange={event => digestField('enabled', event.target.checked)} />Enable WhatsApp traffic digest</label><div className="grid gap-4 sm:grid-cols-2"><label className="store-settings__field"><span>Traffic digest frequency</span><select aria-label="Traffic digest frequency" value={form.whatsappDigest.frequency} onChange={event => digestField('frequency', event.target.value)}><option value="DAILY">Daily</option><option value="WEEKLY">Weekly</option></select></label>{[['recipient', 'Traffic digest WhatsApp recipient', '+919876543210'], ['templateName', 'Approved traffic summary template', 'store_traffic_summary'], ['language', 'Traffic template language', 'en']].map(([key, label, placeholder]) => <label key={key} className="store-settings__field"><span>{label}</span><input aria-label={label} value={form.whatsappDigest[key]} onChange={event => digestField(key, event.target.value)} maxLength={key === 'templateName' ? 100 : 30} placeholder={placeholder} /></label>)}</div><label className="flex gap-3"><input type="checkbox" aria-label="Recipient agrees to receive traffic summaries" checked={form.whatsappDigest.consent} onChange={event => digestField('consent', event.target.checked)} />Recipient agrees to receive traffic summaries</label><details><summary className="cursor-pointer font-semibold">Approved template variables & provider requirements</summary><p className="mt-2">Create a separate approved Meta template with five body variables in this order: store name, period/timezone, measured visitor count, verified order count, secure report link. Example: {'{{1}}'} traffic for {'{{2}}'}: {'{{3}}'}, {'{{4}}'}. View report: {'{{5}}'}. Template approval, business-account setup and provider charges apply. Order-alert templates must not be reused unless their content matches this summary.</p></details>{data.whatsappDigest?.nextRunAt && <p>Next scheduled digest: {new Date(data.whatsappDigest.nextRunAt).toLocaleString('en-IN', { timeZone: data.timezone })} ({data.timezone}). The API must be running for scheduled delivery.</p>}</section>
      <div className="flex flex-wrap gap-3"><button type="button" className="admin-btn" disabled={!dirty || (reducing && !retentionConfirmed)} onClick={() => run(async () => {
        const payload = { ...form, expectedRevision: data.revision, confirmRetentionReduction: retentionConfirmed };
        ['sessionTimeoutMinutes', 'rawRetentionDays', 'summaryRetentionDays', 'attributionDays'].forEach(key => { payload[key] = Number(payload[key]); });
        accept(await api.put(`${apiBase}/traffic`, payload, { silent: true })); announceSettingsSaved(); window.dispatchEvent(new Event('store:traffic-reload')); setNotice('Traffic settings saved. Visitor configuration refreshes in the background.');
      })}>{busy ? 'Working...' : 'Save traffic settings'}</button><button type="button" className="admin-btn-ghost" disabled={!dirty} onClick={() => { setForm(baseline); setRetentionConfirmed(false); }}>Discard changes</button><button type="button" className="admin-btn-ghost" disabled={dirty} onClick={load}>Reload settings</button></div>
    </fieldset>
    {!!data.digestDeliveries?.length && <section className="space-y-3"><h3 className="font-bold">Recent WhatsApp traffic digests</h3>{data.digestDeliveries.map(job => <article key={job._id} className="rounded-xl border border-theme-border p-4 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{job.periodFrom} to {job.periodTo}</strong><span>{job.status === 'ACCEPTED' ? 'Provider accepted' : job.status}</span></div><p className="mt-2 text-theme-muted">{job.reason || 'Waiting for background delivery.'} · Attempts: {job.attempts}</p>{['FAILED', 'UNCERTAIN'].includes(job.status) && <button type="button" className="admin-btn-ghost mt-3" disabled={busy || dirty} onClick={() => job.status === 'UNCERTAIN' ? setUncertainId(job._id) : retryDigest(job._id)}>Retry traffic digest</button>}{uncertainId === job._id && <div role="alert" className="mt-3 rounded-xl bg-amber-50 p-3"><p>Meta might already have accepted this message. Check the provider before retrying.</p><button type="button" className="admin-btn-ghost mt-2" disabled={busy || dirty} onClick={() => { setUncertainId(''); retryDigest(job._id, true); }}>I checked Meta — retry</button><button type="button" className="ml-3" onClick={() => setUncertainId('')}>Cancel</button></div>}</article>)}</section>}
    <details className="rounded-xl border border-red-200 p-4"><summary className="cursor-pointer font-bold text-red-700">Delete this store’s analytics history</summary><p className="my-3 text-sm">Permanently deletes this store’s new traffic events, visitor/session facts and summaries. Orders, customers, payments, stock and other stores are untouched. Earlier legacy marketing history is not part of this traffic-history deletion. Existing browser identities are reset on configuration refresh.</p><label className="store-settings__field"><span>Type DELETE ANALYTICS to confirm</span><input aria-label="Type DELETE ANALYTICS to confirm" value={confirmation} onChange={event => setConfirmation(event.target.value)} /></label><button type="button" className="admin-btn-ghost mt-3" disabled={busy || dirty || confirmation !== 'DELETE ANALYTICS'} onClick={() => run(async () => { await api.post(`${apiBase}/traffic/clear`, { confirmation }, { silent: true }); setConfirmation(''); await load(); setNotice('This store’s traffic history was deleted. Other business data was preserved.'); })}>Permanently delete analytics</button></details>
  </div>;
}
