import { useState } from 'react';
import { Activity, ArrowUpRight, Clock3, Eye, Globe2, Info, MousePointer2, ShieldCheck, Users } from 'lucide-react';
import './TrafficReport.css';
const count = value => new Intl.NumberFormat('en-IN', { maximumFractionDigits: 1 }).format(Number(value || 0));
const states = { disabled: ['Tracking disabled', 'Existing history is available. Enable collection in Settings → Traffic & privacy.'], awaiting_data: ['Waiting for measured traffic', 'Data starts after deployment and eligible visitor consent. No historical visitor counts are invented.'], delayed: ['Analytics processing delayed', 'Collected events are waiting for aggregation. These figures may be incomplete; checkout is unaffected.'], collecting: ['Background collection active', 'Near-real-time analytics, normally refreshed after background processing.'] };
function Panel({ title, note, children }) { return <section className="traffic-report__panel admin-card"><h2>{title}</h2>{note && <p className="traffic-report__muted">{note}</p>}{children}</section>; }
function Rows({ rows = [], visits = false }) {
  if (!rows.length) return <p className="traffic-report__empty">No measured activity in this selection.</p>;
  const max = Math.max(1, ...rows.map(row => visits ? row.sessions : row.value));
  return <div className="traffic-report__rows">{rows.map((row, index) => <div key={`${row.label}-${index}`}><span title={row.label}>{row.label || 'Unknown'}</span><b>{count(visits ? row.sessions : row.value)}</b><i style={{ '--traffic-width': `${(visits ? row.sessions : row.value) / max * 100}%` }} />{visits && <small>{count(row.visitors)} visitors · {count(row.pageViews)} page views</small>}</div>)}</div>;
}
function Trend({ rows = [] }) {
  const [measure, setMeasure] = useState('visitors');
  const max = Math.max(1, ...rows.map(row => row[measure] || 0));
  const points = rows.map((row, index) => `${16 + index * 688 / Math.max(1, rows.length - 1)},${170 - (row[measure] || 0) / max * 150}`).join(' ');
  return <><div className="traffic-report__switch" aria-label="Traffic chart metric">{[['visitors', 'Visitors'], ['sessions', 'Visits'], ['pageViews', 'Page views']].map(([key, label]) => <button type="button" key={key} aria-pressed={measure === key} onClick={() => setMeasure(key)}>{label}</button>)}</div>
    {!rows.length ? <p className="traffic-report__empty">No traffic recorded yet.</p> : <><svg viewBox="0 0 720 190" className="traffic-report__chart" role="img" aria-label={`${measure} across the selected period`}>{[20, 70, 120, 170].map(y => <line key={y} x1="16" x2="704" y1={y} y2={y} className="traffic-report__grid" />)}<polyline points={points} fill="none" className="traffic-report__line" />{rows.map((row, index) => <circle key={row.key} cx={16 + index * 688 / Math.max(1, rows.length - 1)} cy={170 - (row[measure] || 0) / max * 150} r="3"><title>{`${row.key}: ${count(row[measure])} ${measure}`}</title></circle>)}</svg><div className="traffic-report__axis"><span>{rows[0].key}</span><span>{rows.at(-1).key}</span></div><details><summary>View exact traffic values</summary><div className="traffic-report__table"><table><thead><tr><th>Period</th><th>Visitors</th><th>Visits</th><th>Page views</th></tr></thead><tbody>{rows.map(row => <tr key={row.key}><td>{row.key}</td><td>{count(row.visitors)}</td><td>{count(row.sessions)}</td><td>{count(row.pageViews)}</td></tr>)}</tbody></table></div></details></>}
  </>;
}
export default function TrafficReport({ data, base = '/admin', currency = 'INR' }) {
  if (!data) return <p role="status">Traffic report is not available yet.</p>;
  const health = data.health || {}; const status = states[health.state] || states.awaiting_data;
  const metrics = data.metrics || {};
  const timestamp = value => new Date(value).toLocaleString('en-IN', { timeZone: data.timezone || 'Asia/Kolkata' });
  const cards = [['visitors', 'Unique visitors', Users, 'Distinct tracked browser identities across this period, not guaranteed unique people.'], ['sessions', 'Visits', MousePointer2, 'Distinct visits with activity in this period.'], ['pageViews', 'Page views', Eye, 'Refreshes and route navigation count as new page views.'], ['newVisitors', 'New visitors', ArrowUpRight, 'Browser identities first observed in this period.'], ['returningVisitors', 'Returning visitors', Globe2, 'Browser identities observed before this period, within retained history.'], ['averageEngagementSeconds', 'Active seconds / visit', Clock3, 'Foreground interaction time only; background tabs do not accumulate time.']];
  const money = value => new Intl.NumberFormat('en-IN', { style: 'currency', currency }).format(Number(value || 0));
  return <div className="traffic-report">
    <div className={`traffic-report__health is-${health.state || 'awaiting_data'}`} role="status"><Activity size={21} /><div><strong>{status[0]}</strong><p>{status[1]}</p><small>{data.timezone} · Collection started {health.collectionStartedAt ? timestamp(health.collectionStartedAt) : 'not yet'} · Last event {health.lastCollectedAt ? timestamp(health.lastCollectedAt) : 'none'}{health.lagSeconds > 0 ? ` · Processing lag ${health.lagSeconds}s` : ''}</small></div><a href={`${base}/settings`}>Traffic settings</a></div>
    <div className="traffic-report__live"><span><i />{count(data.activeVisitors)} active visitors</span><small>Activity in the last 5 minutes · refreshes every 30 seconds while visible</small></div>
    <div className="traffic-report__kpis">{cards.map(([key, label, Icon, definition]) => <article key={key} className="admin-card" title={definition}><span>{label}<Icon size={18} /></span><strong>{count(metrics[key]?.value)}</strong><small>{metrics[key]?.delta == null ? 'No previous-period baseline' : `${metrics[key].delta > 0 ? '+' : ''}${count(metrics[key].delta)}% vs matched previous period`}</small><p>{definition}</p></article>)}</div>
    {!!data.ignoredFilters?.length && <p className="traffic-report__warning" role="status">Traffic does not use these commerce-only filters: {data.ignoredFilters.join(', ')}. Use source, campaign, device or browser to segment traffic.</p>}
    <Panel title={data.range?.days === 1 ? 'Hourly traffic' : 'Daily traffic'} note={data.definitions?.comparison}><Trend rows={data.series} /></Panel>
    <div className="traffic-report__columns"><Panel title="Visit acquisition" note="Eligible source at visit entry. Purchase attribution uses the most recent eligible non-direct source within the configured window."><Rows rows={data.sources} visits /></Panel><Panel title="First observed source" note="First source retained for an anonymous browser visitor."><Rows rows={data.firstSources} visits /></Panel><Panel title="Campaign performance" note="Visits from tagged campaign links, not external social impressions."><Rows rows={data.campaigns} visits /></Panel><Panel title="Devices"><Rows rows={data.devices} visits /></Panel><Panel title="Browsers"><Rows rows={data.browsers} visits /></Panel><Panel title="Operating systems"><Rows rows={data.operatingSystems} visits /></Panel></div>
    <Panel title="Verified visitor-to-order funnel" note={data.funnel?.note}><div className="traffic-report__funnel">{data.funnel?.steps?.map((step, index) => <article key={step.label}><span>{String(index + 1).padStart(2, '0')}</span><strong>{count(step.value)}</strong><p>{step.label}</p><small>{index ? `${count(step.rate)}% from prior step` : 'Selected starting cohort'}</small></article>)}</div><div className="traffic-report__rates"><span>Full-journey conversion <b>{count(data.funnel?.conversionRate)}%</b></span><span>Engagement rate <b>{count(data.funnel?.engagementRate)}%</b></span><span>Bounce rate <b>{count(data.funnel?.bounceRate)}%</b></span></div></Panel>
    <Panel title="Verified order cohort" note={data.commerce?.note}><div className="traffic-report__rates">{[['Orders placed', 'ordersPlaced'], ['COD placed', 'codPlaced'], ['Online paid', 'onlinePaid'], ['COD collected', 'codCollected'], ['Cancelled', 'cancelled']].map(([label, key]) => <span key={key}>{label}<b>{count(data.commerce?.[key])}</b></span>)}<span>Refunds recorded<b>{money(data.commerce?.refunds)}</b></span></div></Panel>
    {data.retention?.detailsPartial && <p className="traffic-report__warning"><Info size={17} />Detailed page/product/search rankings are available only within the last {data.retention.rawDays} days. Compact traffic totals retain {data.retention.summaryDays} days.</p>}
    <div className="traffic-report__columns">{[['pages', 'Top pages'], ['landings', 'Landing pages'], ['lastPages', 'Last-viewed pages'], ['products', 'Top viewed products'], ['categories', 'Category interactions'], ['searches', 'Store search topics']].map(([key, title]) => <Panel key={key} title={title} note={key === 'lastPages' ? 'Last known page, not proof that the browser closed there.' : key === 'searches' ? 'Catalogue topics only. Sensitive or arbitrary typed phrases are redacted or discarded.' : undefined}><Rows rows={data.details?.[key]} /></Panel>)}</div>
    <details className="traffic-report__definitions admin-card"><summary><ShieldCheck size={18} /> Measurement definitions & privacy</summary>{Object.entries(data.definitions || {}).map(([key, value]) => <p key={key}><strong>{key}: </strong>{value}</p>)}<p>Failed batches recorded: {count(health.failures)}. Last processing: {health.lastProcessedAt ? timestamp(health.lastProcessedAt) : 'not yet'}. This dashboard has no precise-location tracking, session recordings or individual visitor directory.</p></details>
  </div>;
}
